/*
 * This file is generated by jOOQ.
 */
package com.kuvaszuptime.kuvasz;


import com.kuvaszuptime.kuvasz.tables.LatencyLog;
import com.kuvaszuptime.kuvasz.tables.Monitor;
import com.kuvaszuptime.kuvasz.tables.SslEvent;
import com.kuvaszuptime.kuvasz.tables.UptimeEvent;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>latency_log</code>.
     */
    public final LatencyLog LATENCY_LOG = LatencyLog.LATENCY_LOG;

    /**
     * The table <code>monitor</code>.
     */
    public final Monitor MONITOR = Monitor.MONITOR;

    /**
     * The table <code>ssl_event</code>.
     */
    public final SslEvent SSL_EVENT = SslEvent.SSL_EVENT;

    /**
     * The table <code>uptime_event</code>.
     */
    public final UptimeEvent UPTIME_EVENT = UptimeEvent.UPTIME_EVENT;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            LatencyLog.LATENCY_LOG,
            Monitor.MONITOR,
            SslEvent.SSL_EVENT,
            UptimeEvent.UPTIME_EVENT
        );
    }
}
