/*
 * This file is generated by jOOQ.
 */
package com.kuvaszuptime.kuvasz;


import com.kuvaszuptime.kuvasz.tables.LatencyLog;
import com.kuvaszuptime.kuvasz.tables.Monitor;
import com.kuvaszuptime.kuvasz.tables.SslEvent;
import com.kuvaszuptime.kuvasz.tables.UptimeEvent;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Kuvasz extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>kuvasz</code>
     */
    public static final Kuvasz KUVASZ = new Kuvasz();

    /**
     * The table <code>kuvasz.latency_log</code>.
     */
    public final LatencyLog LATENCY_LOG = LatencyLog.LATENCY_LOG;

    /**
     * The table <code>kuvasz.monitor</code>.
     */
    public final Monitor MONITOR = Monitor.MONITOR;

    /**
     * The table <code>kuvasz.ssl_event</code>.
     */
    public final SslEvent SSL_EVENT = SslEvent.SSL_EVENT;

    /**
     * The table <code>kuvasz.uptime_event</code>.
     */
    public final UptimeEvent UPTIME_EVENT = UptimeEvent.UPTIME_EVENT;

    /**
     * No further instances allowed
     */
    private Kuvasz() {
        super("kuvasz", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            LatencyLog.LATENCY_LOG,
            Monitor.MONITOR,
            SslEvent.SSL_EVENT,
            UptimeEvent.UPTIME_EVENT
        );
    }
}
