/*
 * This file is generated by jOOQ.
 */
package com.kuvaszuptime.kuvasz;


import com.kuvaszuptime.kuvasz.tables.LatencyLog;
import com.kuvaszuptime.kuvasz.tables.Monitor;
import com.kuvaszuptime.kuvasz.tables.SslEvent;
import com.kuvaszuptime.kuvasz.tables.UptimeEvent;


/**
 * Convenience access to all tables in kuvasz.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>kuvasz.latency_log</code>.
     */
    public static final LatencyLog LATENCY_LOG = LatencyLog.LATENCY_LOG;

    /**
     * The table <code>kuvasz.monitor</code>.
     */
    public static final Monitor MONITOR = Monitor.MONITOR;

    /**
     * The table <code>kuvasz.ssl_event</code>.
     */
    public static final SslEvent SSL_EVENT = SslEvent.SSL_EVENT;

    /**
     * The table <code>kuvasz.uptime_event</code>.
     */
    public static final UptimeEvent UPTIME_EVENT = UptimeEvent.UPTIME_EVENT;
}
