/*
 * This file is generated by jOOQ.
 */
package com.kuvaszuptime.kuvasz.enums;


import com.kuvaszuptime.kuvasz.DefaultSchema;
import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum UptimeStatus implements EnumType {

    UP("UP"),

    DOWN("DOWN");

    private final String literal;

    private UptimeStatus(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public String getName() {
        return "uptime_status";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static UptimeStatus lookupLiteral(String literal) {
        return EnumType.lookupLiteral(UptimeStatus.class, literal);
    }
}
