micronautVersion=4.10.7
jooqPluginVersion=10.2
jooqVersion=3.20.11
kotlinVersion=2.3.0
kotlinCoroutinesVersion=1.10.2
flywayPluginVersion=12.0.0
detektVersion=2.0.0-alpha.2
# Gradle settings
org.gradle.jvmargs=-Xmx4096M
# Common DB configuration for jOOQ generator & local Flyway migrations
localDbUrl=jdbc:postgresql://localhost:5432/postgres
localDbUser=postgres
localDbPassword=postgres
localDbSchema=kuvasz
localDbDriver=org.postgresql.Driver
