micronautVersion=4.10.7
jooqPluginVersion=10.1.1
jooqVersion=3.20.10
kotlinVersion=2.2.21
kotlinCoroutinesVersion=1.10.2
flywayPluginVersion=11.15.0
detektVersion=1.23.8
# Gradle settings
org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx4096M
# Common DB configuration for jOOQ generator & local Flyway migrations
localDbUrl=jdbc:postgresql://localhost:5432/postgres
localDbUser=postgres
localDbPassword=postgres
localDbSchema=kuvasz
localDbDriver=org.postgresql.Driver
