apiVersion: v1
kind: ConfigMap
metadata:
  name: kuvasz-config
  namespace: kuvasz
data:
  database_host: "database.host"
  database_port: "5432"
  database_name: "postgres"
  enable_auth: "true"
  http_communication_log_enabled: "true"
  log_handler_enabled: "true"
  smtp_event_handler_enabled: "true"
  smtp_host: "smtp.host"
  smtp_port: "587"
  smtp_from_address: "noreply@kuvasz.uptime"
  smtp_to_address: "your.address@example.com"
  smtp_transport_strategy: "SMTP_TLS"
  slack_event_handler_enabled: "true"
  slack_webhook_url: "https://your.slack-webhook.url"
  data_retention_days: "30"
  telegram_event_handler_enabled: "true"
  pagerduty_event_handler_enabled: "true"
