{{- if and .Values.postgresql.enabled .Values.createPostgresqlSecret -}}
{{- if .Values.postgresql.auth.existingSecret -}}
{{- else -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "postgresql" | trunc 63 | trimSuffix "-" }}
  labels:
    app.kubernetes.io/name: {{ include "kuvasz.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "kuvasz.chart" . }}
  annotations:
    helm.sh/resource-policy: keep
    helm.sh/hook: "pre-install"
    helm.sh/hook-delete-policy: "before-hook-creation"
type: Opaque
data:
  {{ $passwordValue := "" }}
  {{- if .Values.postgresql.auth.password }}
  {{- $passwordValue = (.Values.postgresql.auth.password | b64enc | quote) }}
  {{- else }}
  {{- $passwordValue = (randAlphaNum 16 | b64enc | quote) }}
  {{- end }}
  postgresql-password: {{ $passwordValue }}
  postgresql-postgres-password: {{ $passwordValue }}
  {{- $customKey := .Values.postgresql.auth.existingSecretPasswordKey | default "postgresql-password" }}
  {{- if and $customKey (not (or (eq $customKey "postgresql-password") (eq $customKey "postgresql-postgres-password"))) }}
{{ printf "%s: %s" $customKey $passwordValue | indent 2 }}
  {{- end }}
{{- end }}
{{- end }}

