{{- if not .Values.externalAdminSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kuvasz.adminSecretName" . }}
  labels:
    {{- include "kuvasz.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  {{- if .Values.auth.adminUser }}
  admin-user: {{ .Values.auth.adminUser | b64enc | quote }}
  {{- else }}
  admin-user: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  {{- if .Values.auth.adminPassword }}
  admin-password: {{ .Values.auth.adminPassword | b64enc | quote }}
  {{- else }}
  admin-password: {{ randAlphaNum 20 | b64enc | quote }}
  {{- end }}
  {{- if .Values.auth.adminApiKey }}
  admin-api-key: {{ .Values.auth.adminApiKey | b64enc | quote }}
  {{- else }}
  admin-api-key: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
{{- end }}

