{{- if not .Values.postgresql.enabled -}}
{{- if not .Values.externalDatabase.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kuvasz.databaseSecretName" . }}
  labels:
    {{- include "kuvasz.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  {{ .Values.externalDatabase.existingSecretPasswordKey }}: {{ .Values.externalDatabase.password | b64enc | quote }}
{{- end }}
{{- end }}

