ALTER TABLE http_monitor ADD COLUMN category TEXT DEFAULT NULL;
ALTER TABLE push_monitor ADD COLUMN category TEXT DEFAULT NULL;
ALTER TABLE icmp_monitor ADD COLUMN category TEXT DEFAULT NULL;
ALTER TABLE tcp_monitor ADD COLUMN category TEXT DEFAULT NULL;
ALTER TABLE dns_monitor ADD COLUMN category TEXT DEFAULT NULL;
