/*
 * This file is generated by jOOQ.
 */
package com.kuvaszuptime.kuvasz.tables.pojos;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;

import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "latency_log",
    indexes = {
        @Index(name = "latency_log_latency_idx", columnList = "latency ASC"),
        @Index(name = "latency_log_monitor_idx", columnList = "monitor_id ASC")
    }
)
public class LatencyLogPojo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private Integer monitorId;
    private Integer latency;
    private OffsetDateTime createdAt;

    public LatencyLogPojo() {}

    public LatencyLogPojo(LatencyLogPojo value) {
        this.id = value.id;
        this.monitorId = value.monitorId;
        this.latency = value.latency;
        this.createdAt = value.createdAt;
    }

    public LatencyLogPojo(
        Integer id,
        Integer monitorId,
        Integer latency,
        OffsetDateTime createdAt
    ) {
        this.id = id;
        this.monitorId = monitorId;
        this.latency = latency;
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>latency_log.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>latency_log.id</code>.
     */
    public LatencyLogPojo setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>latency_log.monitor_id</code>.
     */
    @Column(name = "monitor_id", nullable = false)
    @NotNull
    public Integer getMonitorId() {
        return this.monitorId;
    }

    /**
     * Setter for <code>latency_log.monitor_id</code>.
     */
    public LatencyLogPojo setMonitorId(Integer monitorId) {
        this.monitorId = monitorId;
        return this;
    }

    /**
     * Getter for <code>latency_log.latency</code>. Lateny in ms
     */
    @Column(name = "latency", nullable = false)
    @NotNull
    public Integer getLatency() {
        return this.latency;
    }

    /**
     * Setter for <code>latency_log.latency</code>. Lateny in ms
     */
    public LatencyLogPojo setLatency(Integer latency) {
        this.latency = latency;
        return this;
    }

    /**
     * Getter for <code>latency_log.created_at</code>.
     */
    @Column(name = "created_at", nullable = false, precision = 6)
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>latency_log.created_at</code>.
     */
    public LatencyLogPojo setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final LatencyLogPojo other = (LatencyLogPojo) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.monitorId == null) {
            if (other.monitorId != null)
                return false;
        }
        else if (!this.monitorId.equals(other.monitorId))
            return false;
        if (this.latency == null) {
            if (other.latency != null)
                return false;
        }
        else if (!this.latency.equals(other.latency))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.monitorId == null) ? 0 : this.monitorId.hashCode());
        result = prime * result + ((this.latency == null) ? 0 : this.latency.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("LatencyLogPojo (");

        sb.append(id);
        sb.append(", ").append(monitorId);
        sb.append(", ").append(latency);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
