/*
 * This file is generated by jOOQ.
 */
package com.kuvaszuptime.kuvasz.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "pagerduty_incident", uniqueConstraints = {
    @UniqueConstraint(name = "pagerduty_incident_pkey", columnNames = {"id"})
}, indexes = {
    @Index(name = "pagerduty_incident_dedup_key_idx", unique = true, columnList = "deduplication_key ASC"),
    @Index(name = "pagerduty_incident_ended_at_idx", columnList = "ended_at ASC"),
    @Index(name = "pagerduty_incident_ssl_event_idx", columnList = "ssl_event_id ASC"),
    @Index(name = "pagerduty_incident_uptime_event_idx", columnList = "uptime_event_id ASC")
})
public class PagerdutyIncidentPojo implements Serializable {

    private static final long serialVersionUID = -922685970;

    private Integer        id;
    private Integer        uptimeEventId;
    private Integer        sslEventId;
    private String         deduplicationKey;
    private OffsetDateTime startedAt;
    private OffsetDateTime endedAt;

    public PagerdutyIncidentPojo() {}

    public PagerdutyIncidentPojo(PagerdutyIncidentPojo value) {
        this.id = value.id;
        this.uptimeEventId = value.uptimeEventId;
        this.sslEventId = value.sslEventId;
        this.deduplicationKey = value.deduplicationKey;
        this.startedAt = value.startedAt;
        this.endedAt = value.endedAt;
    }

    public PagerdutyIncidentPojo(
        Integer        id,
        Integer        uptimeEventId,
        Integer        sslEventId,
        String         deduplicationKey,
        OffsetDateTime startedAt,
        OffsetDateTime endedAt
    ) {
        this.id = id;
        this.uptimeEventId = uptimeEventId;
        this.sslEventId = sslEventId;
        this.deduplicationKey = deduplicationKey;
        this.startedAt = startedAt;
        this.endedAt = endedAt;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false, precision = 32)
    public Integer getId() {
        return this.id;
    }

    public PagerdutyIncidentPojo setId(Integer id) {
        this.id = id;
        return this;
    }

    @Column(name = "uptime_event_id", precision = 32)
    public Integer getUptimeEventId() {
        return this.uptimeEventId;
    }

    public PagerdutyIncidentPojo setUptimeEventId(Integer uptimeEventId) {
        this.uptimeEventId = uptimeEventId;
        return this;
    }

    @Column(name = "ssl_event_id", precision = 32)
    public Integer getSslEventId() {
        return this.sslEventId;
    }

    public PagerdutyIncidentPojo setSslEventId(Integer sslEventId) {
        this.sslEventId = sslEventId;
        return this;
    }

    @Column(name = "deduplication_key", nullable = false, length = 100)
    @NotNull
    @Size(max = 100)
    public String getDeduplicationKey() {
        return this.deduplicationKey;
    }

    public PagerdutyIncidentPojo setDeduplicationKey(String deduplicationKey) {
        this.deduplicationKey = deduplicationKey;
        return this;
    }

    @Column(name = "started_at", nullable = false)
    public OffsetDateTime getStartedAt() {
        return this.startedAt;
    }

    public PagerdutyIncidentPojo setStartedAt(OffsetDateTime startedAt) {
        this.startedAt = startedAt;
        return this;
    }

    @Column(name = "ended_at")
    public OffsetDateTime getEndedAt() {
        return this.endedAt;
    }

    public PagerdutyIncidentPojo setEndedAt(OffsetDateTime endedAt) {
        this.endedAt = endedAt;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PagerdutyIncidentPojo other = (PagerdutyIncidentPojo) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (uptimeEventId == null) {
            if (other.uptimeEventId != null)
                return false;
        }
        else if (!uptimeEventId.equals(other.uptimeEventId))
            return false;
        if (sslEventId == null) {
            if (other.sslEventId != null)
                return false;
        }
        else if (!sslEventId.equals(other.sslEventId))
            return false;
        if (deduplicationKey == null) {
            if (other.deduplicationKey != null)
                return false;
        }
        else if (!deduplicationKey.equals(other.deduplicationKey))
            return false;
        if (startedAt == null) {
            if (other.startedAt != null)
                return false;
        }
        else if (!startedAt.equals(other.startedAt))
            return false;
        if (endedAt == null) {
            if (other.endedAt != null)
                return false;
        }
        else if (!endedAt.equals(other.endedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.uptimeEventId == null) ? 0 : this.uptimeEventId.hashCode());
        result = prime * result + ((this.sslEventId == null) ? 0 : this.sslEventId.hashCode());
        result = prime * result + ((this.deduplicationKey == null) ? 0 : this.deduplicationKey.hashCode());
        result = prime * result + ((this.startedAt == null) ? 0 : this.startedAt.hashCode());
        result = prime * result + ((this.endedAt == null) ? 0 : this.endedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PagerdutyIncidentPojo (");

        sb.append(id);
        sb.append(", ").append(uptimeEventId);
        sb.append(", ").append(sslEventId);
        sb.append(", ").append(deduplicationKey);
        sb.append(", ").append(startedAt);
        sb.append(", ").append(endedAt);

        sb.append(")");
        return sb.toString();
    }
}
