/*
 * This file is generated by jOOQ.
 */
package com.kuvaszuptime.kuvasz.tables.pojos;


import com.kuvaszuptime.kuvasz.enums.SslStatus;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;

import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "ssl_event",
    uniqueConstraints = {
        @UniqueConstraint(name = "ssl_event_key", columnNames = { "monitor_id", "status", "ended_at" })
    },
    indexes = {
        @Index(name = "ssl_event_ended_at_idx", columnList = "ended_at ASC"),
        @Index(name = "ssl_event_monitor_idx", columnList = "monitor_id ASC")
    }
)
public class SslEventPojo implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private Integer monitorId;
    private SslStatus status;
    private String error;
    private OffsetDateTime startedAt;
    private OffsetDateTime endedAt;
    private OffsetDateTime updatedAt;

    public SslEventPojo() {}

    public SslEventPojo(SslEventPojo value) {
        this.id = value.id;
        this.monitorId = value.monitorId;
        this.status = value.status;
        this.error = value.error;
        this.startedAt = value.startedAt;
        this.endedAt = value.endedAt;
        this.updatedAt = value.updatedAt;
    }

    public SslEventPojo(
        Integer id,
        Integer monitorId,
        SslStatus status,
        String error,
        OffsetDateTime startedAt,
        OffsetDateTime endedAt,
        OffsetDateTime updatedAt
    ) {
        this.id = id;
        this.monitorId = monitorId;
        this.status = status;
        this.error = error;
        this.startedAt = startedAt;
        this.endedAt = endedAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>ssl_event.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>ssl_event.id</code>.
     */
    public SslEventPojo setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>ssl_event.monitor_id</code>.
     */
    @Column(name = "monitor_id", nullable = false)
    @NotNull
    public Integer getMonitorId() {
        return this.monitorId;
    }

    /**
     * Setter for <code>ssl_event.monitor_id</code>.
     */
    public SslEventPojo setMonitorId(Integer monitorId) {
        this.monitorId = monitorId;
        return this;
    }

    /**
     * Getter for <code>ssl_event.status</code>. Status of the event
     */
    @Column(name = "status", nullable = false)
    @NotNull
    public SslStatus getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>ssl_event.status</code>. Status of the event
     */
    public SslEventPojo setStatus(SslStatus status) {
        this.status = status;
        return this;
    }

    /**
     * Getter for <code>ssl_event.error</code>.
     */
    @Column(name = "error")
    public String getError() {
        return this.error;
    }

    /**
     * Setter for <code>ssl_event.error</code>.
     */
    public SslEventPojo setError(String error) {
        this.error = error;
        return this;
    }

    /**
     * Getter for <code>ssl_event.started_at</code>. The current event started
     * at
     */
    @Column(name = "started_at", nullable = false, precision = 6)
    public OffsetDateTime getStartedAt() {
        return this.startedAt;
    }

    /**
     * Setter for <code>ssl_event.started_at</code>. The current event started
     * at
     */
    public SslEventPojo setStartedAt(OffsetDateTime startedAt) {
        this.startedAt = startedAt;
        return this;
    }

    /**
     * Getter for <code>ssl_event.ended_at</code>. The current event ended at
     */
    @Column(name = "ended_at", precision = 6)
    public OffsetDateTime getEndedAt() {
        return this.endedAt;
    }

    /**
     * Setter for <code>ssl_event.ended_at</code>. The current event ended at
     */
    public SslEventPojo setEndedAt(OffsetDateTime endedAt) {
        this.endedAt = endedAt;
        return this;
    }

    /**
     * Getter for <code>ssl_event.updated_at</code>.
     */
    @Column(name = "updated_at", nullable = false, precision = 6)
    @NotNull
    public OffsetDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>ssl_event.updated_at</code>.
     */
    public SslEventPojo setUpdatedAt(OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final SslEventPojo other = (SslEventPojo) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.monitorId == null) {
            if (other.monitorId != null)
                return false;
        }
        else if (!this.monitorId.equals(other.monitorId))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.error == null) {
            if (other.error != null)
                return false;
        }
        else if (!this.error.equals(other.error))
            return false;
        if (this.startedAt == null) {
            if (other.startedAt != null)
                return false;
        }
        else if (!this.startedAt.equals(other.startedAt))
            return false;
        if (this.endedAt == null) {
            if (other.endedAt != null)
                return false;
        }
        else if (!this.endedAt.equals(other.endedAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.monitorId == null) ? 0 : this.monitorId.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.error == null) ? 0 : this.error.hashCode());
        result = prime * result + ((this.startedAt == null) ? 0 : this.startedAt.hashCode());
        result = prime * result + ((this.endedAt == null) ? 0 : this.endedAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SslEventPojo (");

        sb.append(id);
        sb.append(", ").append(monitorId);
        sb.append(", ").append(status);
        sb.append(", ").append(error);
        sb.append(", ").append(startedAt);
        sb.append(", ").append(endedAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
