/*
 * This file is generated by jOOQ.
 */
package com.kuvaszuptime.kuvasz.jooq.tables.records;


import com.kuvaszuptime.kuvasz.jooq.MonitorWithMetricsHistory;
import com.kuvaszuptime.kuvasz.jooq.SchedulableMonitorRecord;
import com.kuvaszuptime.kuvasz.jooq.enums.DnsResponseCode;
import com.kuvaszuptime.kuvasz.jooq.enums.DnsTransport;
import com.kuvaszuptime.kuvasz.jooq.tables.DnsMonitor;
import com.kuvaszuptime.kuvasz.models.handlers.IntegrationID;
import com.kuvaszuptime.kuvasz.models.monitor.dns.DnsRecordType;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import tools.jackson.databind.JsonNode;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DnsMonitorRecord extends UpdatableRecordImpl<DnsMonitorRecord> implements SchedulableMonitorRecord, MonitorWithMetricsHistory {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>kuvasz.dns_monitor.id</code>.
     */
    public DnsMonitorRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.dns_monitor.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>kuvasz.dns_monitor.name</code>.
     */
    public DnsMonitorRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.dns_monitor.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>kuvasz.dns_monitor.host</code>.
     */
    public DnsMonitorRecord setHost(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.dns_monitor.host</code>.
     */
    public String getHost() {
        return (String) get(2);
    }

    /**
     * Setter for <code>kuvasz.dns_monitor.resolver_host</code>.
     */
    public DnsMonitorRecord setResolverHost(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.dns_monitor.resolver_host</code>.
     */
    public String getResolverHost() {
        return (String) get(3);
    }

    /**
     * Setter for <code>kuvasz.dns_monitor.resolver_port</code>.
     */
    public DnsMonitorRecord setResolverPort(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.dns_monitor.resolver_port</code>.
     */
    public Integer getResolverPort() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>kuvasz.dns_monitor.transport</code>.
     */
    public DnsMonitorRecord setTransport(DnsTransport value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.dns_monitor.transport</code>.
     */
    public DnsTransport getTransport() {
        return (DnsTransport) get(5);
    }

    /**
     * Setter for <code>kuvasz.dns_monitor.record_matchers</code>.
     */
    public DnsMonitorRecord setRecordMatchers(JsonNode value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.dns_monitor.record_matchers</code>.
     */
    public JsonNode getRecordMatchers() {
        return (JsonNode) get(6);
    }

    /**
     * Setter for <code>kuvasz.dns_monitor.expected_response_code</code>.
     */
    public DnsMonitorRecord setExpectedResponseCode(DnsResponseCode value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.dns_monitor.expected_response_code</code>.
     */
    public DnsResponseCode getExpectedResponseCode() {
        return (DnsResponseCode) get(7);
    }

    /**
     * Setter for <code>kuvasz.dns_monitor.drift_detection_enabled</code>.
     */
    public DnsMonitorRecord setDriftDetectionEnabled(Boolean value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.dns_monitor.drift_detection_enabled</code>.
     */
    public Boolean getDriftDetectionEnabled() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>kuvasz.dns_monitor.drift_record_types</code>.
     */
    public DnsMonitorRecord setDriftRecordTypes(DnsRecordType[] value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.dns_monitor.drift_record_types</code>.
     */
    public DnsRecordType[] getDriftRecordTypes() {
        return (DnsRecordType[]) get(9);
    }

    /**
     * Setter for <code>kuvasz.dns_monitor.uptime_check_interval</code>.
     */
    public DnsMonitorRecord setUptimeCheckInterval(Integer value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.dns_monitor.uptime_check_interval</code>.
     */
    public Integer getUptimeCheckInterval() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>kuvasz.dns_monitor.timeout_ms</code>.
     */
    public DnsMonitorRecord setTimeoutMs(Integer value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.dns_monitor.timeout_ms</code>.
     */
    public Integer getTimeoutMs() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>kuvasz.dns_monitor.latency_threshold_ms</code>.
     */
    public DnsMonitorRecord setLatencyThresholdMs(Integer value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.dns_monitor.latency_threshold_ms</code>.
     */
    public Integer getLatencyThresholdMs() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>kuvasz.dns_monitor.failure_count_threshold</code>.
     */
    public DnsMonitorRecord setFailureCountThreshold(Long value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.dns_monitor.failure_count_threshold</code>.
     */
    public Long getFailureCountThreshold() {
        return (Long) get(13);
    }

    /**
     * Setter for <code>kuvasz.dns_monitor.enabled</code>.
     */
    public DnsMonitorRecord setEnabled(Boolean value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.dns_monitor.enabled</code>.
     */
    public Boolean getEnabled() {
        return (Boolean) get(14);
    }

    /**
     * Setter for <code>kuvasz.dns_monitor.metrics_history_enabled</code>.
     */
    public DnsMonitorRecord setMetricsHistoryEnabled(Boolean value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.dns_monitor.metrics_history_enabled</code>.
     */
    public Boolean getMetricsHistoryEnabled() {
        return (Boolean) get(15);
    }

    /**
     * Setter for <code>kuvasz.dns_monitor.integrations</code>.
     */
    public DnsMonitorRecord setIntegrations(IntegrationID[] value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.dns_monitor.integrations</code>.
     */
    public IntegrationID[] getIntegrations() {
        return (IntegrationID[]) get(16);
    }

    /**
     * Setter for <code>kuvasz.dns_monitor.created_at</code>.
     */
    public DnsMonitorRecord setCreatedAt(OffsetDateTime value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.dns_monitor.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(17);
    }

    /**
     * Setter for <code>kuvasz.dns_monitor.updated_at</code>.
     */
    public DnsMonitorRecord setUpdatedAt(OffsetDateTime value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.dns_monitor.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(18);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DnsMonitorRecord
     */
    public DnsMonitorRecord() {
        super(DnsMonitor.DNS_MONITOR);
    }

    /**
     * Create a detached, initialised DnsMonitorRecord
     */
    public DnsMonitorRecord(Long id, String name, String host, String resolverHost, Integer resolverPort, DnsTransport transport, JsonNode recordMatchers, DnsResponseCode expectedResponseCode, Boolean driftDetectionEnabled, DnsRecordType[] driftRecordTypes, Integer uptimeCheckInterval, Integer timeoutMs, Integer latencyThresholdMs, Long failureCountThreshold, Boolean enabled, Boolean metricsHistoryEnabled, IntegrationID[] integrations, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        super(DnsMonitor.DNS_MONITOR);

        setId(id);
        setName(name);
        setHost(host);
        setResolverHost(resolverHost);
        setResolverPort(resolverPort);
        setTransport(transport);
        setRecordMatchers(recordMatchers);
        setExpectedResponseCode(expectedResponseCode);
        setDriftDetectionEnabled(driftDetectionEnabled);
        setDriftRecordTypes(driftRecordTypes);
        setUptimeCheckInterval(uptimeCheckInterval);
        setTimeoutMs(timeoutMs);
        setLatencyThresholdMs(latencyThresholdMs);
        setFailureCountThreshold(failureCountThreshold);
        setEnabled(enabled);
        setMetricsHistoryEnabled(metricsHistoryEnabled);
        setIntegrations(integrations);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised DnsMonitorRecord
     */
    public DnsMonitorRecord(com.kuvaszuptime.kuvasz.jooq.tables.pojos.DnsMonitor value) {
        super(DnsMonitor.DNS_MONITOR);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setHost(value.getHost());
            setResolverHost(value.getResolverHost());
            setResolverPort(value.getResolverPort());
            setTransport(value.getTransport());
            setRecordMatchers(value.getRecordMatchers());
            setExpectedResponseCode(value.getExpectedResponseCode());
            setDriftDetectionEnabled(value.getDriftDetectionEnabled());
            setDriftRecordTypes(value.getDriftRecordTypes());
            setUptimeCheckInterval(value.getUptimeCheckInterval());
            setTimeoutMs(value.getTimeoutMs());
            setLatencyThresholdMs(value.getLatencyThresholdMs());
            setFailureCountThreshold(value.getFailureCountThreshold());
            setEnabled(value.getEnabled());
            setMetricsHistoryEnabled(value.getMetricsHistoryEnabled());
            setIntegrations(value.getIntegrations());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetTouchedOnNotNull();
        }
    }
}
