/*
 * This file is generated by jOOQ.
 */
package com.kuvaszuptime.kuvasz.jooq.tables.records;


import com.kuvaszuptime.kuvasz.jooq.tables.DnsMetricsLog;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DnsMetricsLogRecord extends UpdatableRecordImpl<DnsMetricsLogRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>kuvasz.dns_metrics_log.id</code>.
     */
    public DnsMetricsLogRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.dns_metrics_log.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>kuvasz.dns_metrics_log.monitor_id</code>.
     */
    public DnsMetricsLogRecord setMonitorId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.dns_metrics_log.monitor_id</code>.
     */
    public Long getMonitorId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>kuvasz.dns_metrics_log.latency_ms</code>.
     */
    public DnsMetricsLogRecord setLatencyMs(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.dns_metrics_log.latency_ms</code>.
     */
    public Integer getLatencyMs() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>kuvasz.dns_metrics_log.created_at</code>.
     */
    public DnsMetricsLogRecord setCreatedAt(OffsetDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.dns_metrics_log.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DnsMetricsLogRecord
     */
    public DnsMetricsLogRecord() {
        super(DnsMetricsLog.DNS_METRICS_LOG);
    }

    /**
     * Create a detached, initialised DnsMetricsLogRecord
     */
    public DnsMetricsLogRecord(Long id, Long monitorId, Integer latencyMs, OffsetDateTime createdAt) {
        super(DnsMetricsLog.DNS_METRICS_LOG);

        setId(id);
        setMonitorId(monitorId);
        setLatencyMs(latencyMs);
        setCreatedAt(createdAt);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised DnsMetricsLogRecord
     */
    public DnsMetricsLogRecord(com.kuvaszuptime.kuvasz.jooq.tables.pojos.DnsMetricsLog value) {
        super(DnsMetricsLog.DNS_METRICS_LOG);

        if (value != null) {
            setId(value.getId());
            setMonitorId(value.getMonitorId());
            setLatencyMs(value.getLatencyMs());
            setCreatedAt(value.getCreatedAt());
            resetTouchedOnNotNull();
        }
    }
}
