/*
 * This file is generated by jOOQ.
 */
package com.kuvaszuptime.kuvasz.jooq.tables.records;


import com.kuvaszuptime.kuvasz.jooq.tables.DnsResolutionSnapshot;

import java.time.OffsetDateTime;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DnsResolutionSnapshotRecord extends UpdatableRecordImpl<DnsResolutionSnapshotRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>kuvasz.dns_resolution_snapshot.monitor_id</code>.
     */
    public DnsResolutionSnapshotRecord setMonitorId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.dns_resolution_snapshot.monitor_id</code>.
     */
    public Long getMonitorId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>kuvasz.dns_resolution_snapshot.records</code>.
     */
    public DnsResolutionSnapshotRecord setRecords(JSONB value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.dns_resolution_snapshot.records</code>.
     */
    public JSONB getRecords() {
        return (JSONB) get(1);
    }

    /**
     * Setter for <code>kuvasz.dns_resolution_snapshot.updated_at</code>.
     */
    public DnsResolutionSnapshotRecord setUpdatedAt(OffsetDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.dns_resolution_snapshot.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DnsResolutionSnapshotRecord
     */
    public DnsResolutionSnapshotRecord() {
        super(DnsResolutionSnapshot.DNS_RESOLUTION_SNAPSHOT);
    }

    /**
     * Create a detached, initialised DnsResolutionSnapshotRecord
     */
    public DnsResolutionSnapshotRecord(Long monitorId, JSONB records, OffsetDateTime updatedAt) {
        super(DnsResolutionSnapshot.DNS_RESOLUTION_SNAPSHOT);

        setMonitorId(monitorId);
        setRecords(records);
        setUpdatedAt(updatedAt);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised DnsResolutionSnapshotRecord
     */
    public DnsResolutionSnapshotRecord(com.kuvaszuptime.kuvasz.jooq.tables.pojos.DnsResolutionSnapshot value) {
        super(DnsResolutionSnapshot.DNS_RESOLUTION_SNAPSHOT);

        if (value != null) {
            setMonitorId(value.getMonitorId());
            setRecords(value.getRecords());
            setUpdatedAt(value.getUpdatedAt());
            resetTouchedOnNotNull();
        }
    }
}
