/*
 * This file is generated by jOOQ.
 */
package com.kuvaszuptime.kuvasz.jooq.tables.records;


import com.kuvaszuptime.kuvasz.jooq.MonitorWithMetricsHistory;
import com.kuvaszuptime.kuvasz.jooq.SchedulableMonitorRecord;
import com.kuvaszuptime.kuvasz.jooq.tables.DockerMonitor;
import com.kuvaszuptime.kuvasz.models.handlers.IntegrationID;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DockerMonitorRecord extends UpdatableRecordImpl<DockerMonitorRecord> implements SchedulableMonitorRecord, MonitorWithMetricsHistory {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>kuvasz.docker_monitor.id</code>.
     */
    public DockerMonitorRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.docker_monitor.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>kuvasz.docker_monitor.name</code>.
     */
    public DockerMonitorRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.docker_monitor.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>kuvasz.docker_monitor.docker_host</code>.
     */
    public DockerMonitorRecord setDockerHost(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.docker_monitor.docker_host</code>.
     */
    public String getDockerHost() {
        return (String) get(2);
    }

    /**
     * Setter for <code>kuvasz.docker_monitor.container</code>.
     */
    public DockerMonitorRecord setContainer(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.docker_monitor.container</code>.
     */
    public String getContainer() {
        return (String) get(3);
    }

    /**
     * Setter for <code>kuvasz.docker_monitor.uptime_check_interval</code>.
     */
    public DockerMonitorRecord setUptimeCheckInterval(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.docker_monitor.uptime_check_interval</code>.
     */
    public Integer getUptimeCheckInterval() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>kuvasz.docker_monitor.timeout_ms</code>.
     */
    public DockerMonitorRecord setTimeoutMs(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.docker_monitor.timeout_ms</code>.
     */
    public Integer getTimeoutMs() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>kuvasz.docker_monitor.failure_count_threshold</code>.
     */
    public DockerMonitorRecord setFailureCountThreshold(Long value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.docker_monitor.failure_count_threshold</code>.
     */
    public Long getFailureCountThreshold() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>kuvasz.docker_monitor.enabled</code>.
     */
    public DockerMonitorRecord setEnabled(Boolean value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.docker_monitor.enabled</code>.
     */
    public Boolean getEnabled() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>kuvasz.docker_monitor.metrics_history_enabled</code>.
     */
    public DockerMonitorRecord setMetricsHistoryEnabled(Boolean value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.docker_monitor.metrics_history_enabled</code>.
     */
    public Boolean getMetricsHistoryEnabled() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>kuvasz.docker_monitor.integrations</code>.
     */
    public DockerMonitorRecord setIntegrations(IntegrationID[] value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.docker_monitor.integrations</code>.
     */
    public IntegrationID[] getIntegrations() {
        return (IntegrationID[]) get(9);
    }

    /**
     * Setter for <code>kuvasz.docker_monitor.category</code>.
     */
    public DockerMonitorRecord setCategory(String value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.docker_monitor.category</code>.
     */
    public String getCategory() {
        return (String) get(10);
    }

    /**
     * Setter for <code>kuvasz.docker_monitor.ignore_connectivity_check</code>.
     */
    public DockerMonitorRecord setIgnoreConnectivityCheck(Boolean value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.docker_monitor.ignore_connectivity_check</code>.
     */
    public Boolean getIgnoreConnectivityCheck() {
        return (Boolean) get(11);
    }

    /**
     * Setter for <code>kuvasz.docker_monitor.created_at</code>.
     */
    public DockerMonitorRecord setCreatedAt(OffsetDateTime value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.docker_monitor.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(12);
    }

    /**
     * Setter for <code>kuvasz.docker_monitor.updated_at</code>.
     */
    public DockerMonitorRecord setUpdatedAt(OffsetDateTime value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.docker_monitor.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DockerMonitorRecord
     */
    public DockerMonitorRecord() {
        super(DockerMonitor.DOCKER_MONITOR);
    }

    /**
     * Create a detached, initialised DockerMonitorRecord
     */
    public DockerMonitorRecord(Long id, String name, String dockerHost, String container, Integer uptimeCheckInterval, Integer timeoutMs, Long failureCountThreshold, Boolean enabled, Boolean metricsHistoryEnabled, IntegrationID[] integrations, String category, Boolean ignoreConnectivityCheck, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        super(DockerMonitor.DOCKER_MONITOR);

        setId(id);
        setName(name);
        setDockerHost(dockerHost);
        setContainer(container);
        setUptimeCheckInterval(uptimeCheckInterval);
        setTimeoutMs(timeoutMs);
        setFailureCountThreshold(failureCountThreshold);
        setEnabled(enabled);
        setMetricsHistoryEnabled(metricsHistoryEnabled);
        setIntegrations(integrations);
        setCategory(category);
        setIgnoreConnectivityCheck(ignoreConnectivityCheck);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised DockerMonitorRecord
     */
    public DockerMonitorRecord(com.kuvaszuptime.kuvasz.jooq.tables.pojos.DockerMonitor value) {
        super(DockerMonitor.DOCKER_MONITOR);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setDockerHost(value.getDockerHost());
            setContainer(value.getContainer());
            setUptimeCheckInterval(value.getUptimeCheckInterval());
            setTimeoutMs(value.getTimeoutMs());
            setFailureCountThreshold(value.getFailureCountThreshold());
            setEnabled(value.getEnabled());
            setMetricsHistoryEnabled(value.getMetricsHistoryEnabled());
            setIntegrations(value.getIntegrations());
            setCategory(value.getCategory());
            setIgnoreConnectivityCheck(value.getIgnoreConnectivityCheck());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetTouchedOnNotNull();
        }
    }
}
