/*
 * This file is generated by jOOQ.
 */
package com.kuvaszuptime.kuvasz.jooq.tables.records;


import com.kuvaszuptime.kuvasz.jooq.tables.HttpLatencyLog;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class HttpLatencyLogRecord extends UpdatableRecordImpl<HttpLatencyLogRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>kuvasz.http_latency_log.id</code>.
     */
    public HttpLatencyLogRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.http_latency_log.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>kuvasz.http_latency_log.monitor_id</code>.
     */
    public HttpLatencyLogRecord setMonitorId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.http_latency_log.monitor_id</code>.
     */
    public Long getMonitorId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>kuvasz.http_latency_log.latency</code>. Lateny in ms
     */
    public HttpLatencyLogRecord setLatency(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.http_latency_log.latency</code>. Lateny in ms
     */
    public Integer getLatency() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>kuvasz.http_latency_log.created_at</code>.
     */
    public HttpLatencyLogRecord setCreatedAt(OffsetDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.http_latency_log.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HttpLatencyLogRecord
     */
    public HttpLatencyLogRecord() {
        super(HttpLatencyLog.HTTP_LATENCY_LOG);
    }

    /**
     * Create a detached, initialised HttpLatencyLogRecord
     */
    public HttpLatencyLogRecord(Long id, Long monitorId, Integer latency, OffsetDateTime createdAt) {
        super(HttpLatencyLog.HTTP_LATENCY_LOG);

        setId(id);
        setMonitorId(monitorId);
        setLatency(latency);
        setCreatedAt(createdAt);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised HttpLatencyLogRecord
     */
    public HttpLatencyLogRecord(com.kuvaszuptime.kuvasz.jooq.tables.pojos.HttpLatencyLog value) {
        super(HttpLatencyLog.HTTP_LATENCY_LOG);

        if (value != null) {
            setId(value.getId());
            setMonitorId(value.getMonitorId());
            setLatency(value.getLatency());
            setCreatedAt(value.getCreatedAt());
            resetTouchedOnNotNull();
        }
    }
}
