/*
 * This file is generated by jOOQ.
 */
package com.kuvaszuptime.kuvasz.jooq.tables.records;


import com.kuvaszuptime.kuvasz.jooq.tables.IcmpMetricsLog;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class IcmpMetricsLogRecord extends UpdatableRecordImpl<IcmpMetricsLogRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>kuvasz.icmp_metrics_log.id</code>.
     */
    public IcmpMetricsLogRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.icmp_metrics_log.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>kuvasz.icmp_metrics_log.monitor_id</code>.
     */
    public IcmpMetricsLogRecord setMonitorId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.icmp_metrics_log.monitor_id</code>.
     */
    public Long getMonitorId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>kuvasz.icmp_metrics_log.latency_ms</code>.
     */
    public IcmpMetricsLogRecord setLatencyMs(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.icmp_metrics_log.latency_ms</code>.
     */
    public Integer getLatencyMs() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>kuvasz.icmp_metrics_log.packet_loss_percentage</code>.
     */
    public IcmpMetricsLogRecord setPacketLossPercentage(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.icmp_metrics_log.packet_loss_percentage</code>.
     */
    public Integer getPacketLossPercentage() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>kuvasz.icmp_metrics_log.created_at</code>.
     */
    public IcmpMetricsLogRecord setCreatedAt(OffsetDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.icmp_metrics_log.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IcmpMetricsLogRecord
     */
    public IcmpMetricsLogRecord() {
        super(IcmpMetricsLog.ICMP_METRICS_LOG);
    }

    /**
     * Create a detached, initialised IcmpMetricsLogRecord
     */
    public IcmpMetricsLogRecord(Long id, Long monitorId, Integer latencyMs, Integer packetLossPercentage, OffsetDateTime createdAt) {
        super(IcmpMetricsLog.ICMP_METRICS_LOG);

        setId(id);
        setMonitorId(monitorId);
        setLatencyMs(latencyMs);
        setPacketLossPercentage(packetLossPercentage);
        setCreatedAt(createdAt);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised IcmpMetricsLogRecord
     */
    public IcmpMetricsLogRecord(com.kuvaszuptime.kuvasz.jooq.tables.pojos.IcmpMetricsLog value) {
        super(IcmpMetricsLog.ICMP_METRICS_LOG);

        if (value != null) {
            setId(value.getId());
            setMonitorId(value.getMonitorId());
            setLatencyMs(value.getLatencyMs());
            setPacketLossPercentage(value.getPacketLossPercentage());
            setCreatedAt(value.getCreatedAt());
            resetTouchedOnNotNull();
        }
    }
}
