/*
 * This file is generated by jOOQ.
 */
package com.kuvaszuptime.kuvasz.jooq.tables.records;


import com.kuvaszuptime.kuvasz.jooq.UptimeEventRecord;
import com.kuvaszuptime.kuvasz.jooq.enums.UptimeStatus;
import com.kuvaszuptime.kuvasz.jooq.tables.IcmpUptimeEvent;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class IcmpUptimeEventRecord extends UpdatableRecordImpl<IcmpUptimeEventRecord> implements UptimeEventRecord {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>kuvasz.icmp_uptime_event.id</code>.
     */
    public IcmpUptimeEventRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.icmp_uptime_event.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>kuvasz.icmp_uptime_event.monitor_id</code>.
     */
    public IcmpUptimeEventRecord setMonitorId(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.icmp_uptime_event.monitor_id</code>.
     */
    public Long getMonitorId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>kuvasz.icmp_uptime_event.status</code>.
     */
    public IcmpUptimeEventRecord setStatus(UptimeStatus value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.icmp_uptime_event.status</code>.
     */
    public UptimeStatus getStatus() {
        return (UptimeStatus) get(2);
    }

    /**
     * Setter for <code>kuvasz.icmp_uptime_event.error</code>.
     */
    public IcmpUptimeEventRecord setError(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.icmp_uptime_event.error</code>.
     */
    public String getError() {
        return (String) get(3);
    }

    /**
     * Setter for <code>kuvasz.icmp_uptime_event.started_at</code>.
     */
    public IcmpUptimeEventRecord setStartedAt(OffsetDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.icmp_uptime_event.started_at</code>.
     */
    public OffsetDateTime getStartedAt() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>kuvasz.icmp_uptime_event.ended_at</code>.
     */
    public IcmpUptimeEventRecord setEndedAt(OffsetDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.icmp_uptime_event.ended_at</code>.
     */
    public OffsetDateTime getEndedAt() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>kuvasz.icmp_uptime_event.updated_at</code>.
     */
    public IcmpUptimeEventRecord setUpdatedAt(OffsetDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.icmp_uptime_event.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IcmpUptimeEventRecord
     */
    public IcmpUptimeEventRecord() {
        super(IcmpUptimeEvent.ICMP_UPTIME_EVENT);
    }

    /**
     * Create a detached, initialised IcmpUptimeEventRecord
     */
    public IcmpUptimeEventRecord(Long id, Long monitorId, UptimeStatus status, String error, OffsetDateTime startedAt, OffsetDateTime endedAt, OffsetDateTime updatedAt) {
        super(IcmpUptimeEvent.ICMP_UPTIME_EVENT);

        setId(id);
        setMonitorId(monitorId);
        setStatus(status);
        setError(error);
        setStartedAt(startedAt);
        setEndedAt(endedAt);
        setUpdatedAt(updatedAt);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised IcmpUptimeEventRecord
     */
    public IcmpUptimeEventRecord(com.kuvaszuptime.kuvasz.jooq.tables.pojos.IcmpUptimeEvent value) {
        super(IcmpUptimeEvent.ICMP_UPTIME_EVENT);

        if (value != null) {
            setId(value.getId());
            setMonitorId(value.getMonitorId());
            setStatus(value.getStatus());
            setError(value.getError());
            setStartedAt(value.getStartedAt());
            setEndedAt(value.getEndedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetTouchedOnNotNull();
        }
    }
}
