/*
 * This file is generated by jOOQ.
 */
package com.kuvaszuptime.kuvasz.jooq.tables.records;


import com.kuvaszuptime.kuvasz.jooq.MonitorRecord;
import com.kuvaszuptime.kuvasz.jooq.tables.IcmpMonitor;
import com.kuvaszuptime.kuvasz.models.handlers.IntegrationID;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class IcmpMonitorRecord extends UpdatableRecordImpl<IcmpMonitorRecord> implements MonitorRecord {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>kuvasz.icmp_monitor.id</code>.
     */
    public IcmpMonitorRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.icmp_monitor.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>kuvasz.icmp_monitor.name</code>.
     */
    public IcmpMonitorRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.icmp_monitor.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>kuvasz.icmp_monitor.host</code>.
     */
    public IcmpMonitorRecord setHost(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.icmp_monitor.host</code>.
     */
    public String getHost() {
        return (String) get(2);
    }

    /**
     * Setter for <code>kuvasz.icmp_monitor.uptime_check_interval</code>.
     */
    public IcmpMonitorRecord setUptimeCheckInterval(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.icmp_monitor.uptime_check_interval</code>.
     */
    public Integer getUptimeCheckInterval() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>kuvasz.icmp_monitor.packet_count</code>.
     */
    public IcmpMonitorRecord setPacketCount(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.icmp_monitor.packet_count</code>.
     */
    public Integer getPacketCount() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>kuvasz.icmp_monitor.timeout_seconds</code>.
     */
    public IcmpMonitorRecord setTimeoutSeconds(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.icmp_monitor.timeout_seconds</code>.
     */
    public Integer getTimeoutSeconds() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>kuvasz.icmp_monitor.packet_loss_threshold</code>.
     */
    public IcmpMonitorRecord setPacketLossThreshold(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.icmp_monitor.packet_loss_threshold</code>.
     */
    public Integer getPacketLossThreshold() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>kuvasz.icmp_monitor.failure_count_threshold</code>.
     */
    public IcmpMonitorRecord setFailureCountThreshold(Long value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.icmp_monitor.failure_count_threshold</code>.
     */
    public Long getFailureCountThreshold() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>kuvasz.icmp_monitor.enabled</code>.
     */
    public IcmpMonitorRecord setEnabled(Boolean value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.icmp_monitor.enabled</code>.
     */
    public Boolean getEnabled() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>kuvasz.icmp_monitor.metrics_history_enabled</code>.
     */
    public IcmpMonitorRecord setMetricsHistoryEnabled(Boolean value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.icmp_monitor.metrics_history_enabled</code>.
     */
    public Boolean getMetricsHistoryEnabled() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>kuvasz.icmp_monitor.integrations</code>.
     */
    public IcmpMonitorRecord setIntegrations(IntegrationID[] value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.icmp_monitor.integrations</code>.
     */
    public IntegrationID[] getIntegrations() {
        return (IntegrationID[]) get(10);
    }

    /**
     * Setter for <code>kuvasz.icmp_monitor.created_at</code>.
     */
    public IcmpMonitorRecord setCreatedAt(OffsetDateTime value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.icmp_monitor.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(11);
    }

    /**
     * Setter for <code>kuvasz.icmp_monitor.updated_at</code>.
     */
    public IcmpMonitorRecord setUpdatedAt(OffsetDateTime value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.icmp_monitor.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached IcmpMonitorRecord
     */
    public IcmpMonitorRecord() {
        super(IcmpMonitor.ICMP_MONITOR);
    }

    /**
     * Create a detached, initialised IcmpMonitorRecord
     */
    public IcmpMonitorRecord(Long id, String name, String host, Integer uptimeCheckInterval, Integer packetCount, Integer timeoutSeconds, Integer packetLossThreshold, Long failureCountThreshold, Boolean enabled, Boolean metricsHistoryEnabled, IntegrationID[] integrations, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        super(IcmpMonitor.ICMP_MONITOR);

        setId(id);
        setName(name);
        setHost(host);
        setUptimeCheckInterval(uptimeCheckInterval);
        setPacketCount(packetCount);
        setTimeoutSeconds(timeoutSeconds);
        setPacketLossThreshold(packetLossThreshold);
        setFailureCountThreshold(failureCountThreshold);
        setEnabled(enabled);
        setMetricsHistoryEnabled(metricsHistoryEnabled);
        setIntegrations(integrations);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised IcmpMonitorRecord
     */
    public IcmpMonitorRecord(com.kuvaszuptime.kuvasz.jooq.tables.pojos.IcmpMonitor value) {
        super(IcmpMonitor.ICMP_MONITOR);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setHost(value.getHost());
            setUptimeCheckInterval(value.getUptimeCheckInterval());
            setPacketCount(value.getPacketCount());
            setTimeoutSeconds(value.getTimeoutSeconds());
            setPacketLossThreshold(value.getPacketLossThreshold());
            setFailureCountThreshold(value.getFailureCountThreshold());
            setEnabled(value.getEnabled());
            setMetricsHistoryEnabled(value.getMetricsHistoryEnabled());
            setIntegrations(value.getIntegrations());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetTouchedOnNotNull();
        }
    }
}
