/*
 * This file is generated by jOOQ.
 */
package com.kuvaszuptime.kuvasz.jooq.tables.records;


import com.kuvaszuptime.kuvasz.jooq.tables.PendingFailure;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PendingFailureRecord extends UpdatableRecordImpl<PendingFailureRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>kuvasz.pending_failure.monitor_id</code>.
     */
    public PendingFailureRecord setMonitorId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.pending_failure.monitor_id</code>.
     */
    public Long getMonitorId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>kuvasz.pending_failure.failure_count</code>.
     */
    public PendingFailureRecord setFailureCount(Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.pending_failure.failure_count</code>.
     */
    public Long getFailureCount() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>kuvasz.pending_failure.created_at</code>.
     */
    public PendingFailureRecord setCreatedAt(OffsetDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.pending_failure.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>kuvasz.pending_failure.updated_at</code>.
     */
    public PendingFailureRecord setUpdatedAt(OffsetDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.pending_failure.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PendingFailureRecord
     */
    public PendingFailureRecord() {
        super(PendingFailure.PENDING_FAILURE);
    }

    /**
     * Create a detached, initialised PendingFailureRecord
     */
    public PendingFailureRecord(Long monitorId, Long failureCount, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        super(PendingFailure.PENDING_FAILURE);

        setMonitorId(monitorId);
        setFailureCount(failureCount);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised PendingFailureRecord
     */
    public PendingFailureRecord(com.kuvaszuptime.kuvasz.jooq.tables.pojos.PendingFailure value) {
        super(PendingFailure.PENDING_FAILURE);

        if (value != null) {
            setMonitorId(value.getMonitorId());
            setFailureCount(value.getFailureCount());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetTouchedOnNotNull();
        }
    }
}
