/*
 * This file is generated by jOOQ.
 */
package com.kuvaszuptime.kuvasz.jooq.tables.records;


import com.kuvaszuptime.kuvasz.jooq.tables.StatusPage;
import com.kuvaszuptime.kuvasz.models.MonitorID;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class StatusPageRecord extends UpdatableRecordImpl<StatusPageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>kuvasz.status_page.id</code>.
     */
    public StatusPageRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.status_page.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>kuvasz.status_page.title</code>.
     */
    public StatusPageRecord setTitle(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.status_page.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>kuvasz.status_page.slug</code>.
     */
    public StatusPageRecord setSlug(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.status_page.slug</code>.
     */
    public String getSlug() {
        return (String) get(2);
    }

    /**
     * Setter for <code>kuvasz.status_page.enabled</code>.
     */
    public StatusPageRecord setEnabled(Boolean value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.status_page.enabled</code>.
     */
    public Boolean getEnabled() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>kuvasz.status_page.monitors</code>.
     */
    public StatusPageRecord setMonitors(MonitorID[] value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.status_page.monitors</code>.
     */
    public MonitorID[] getMonitors() {
        return (MonitorID[]) get(4);
    }

    /**
     * Setter for <code>kuvasz.status_page.created_at</code>.
     */
    public StatusPageRecord setCreatedAt(OffsetDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.status_page.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>kuvasz.status_page.updated_at</code>.
     */
    public StatusPageRecord setUpdatedAt(OffsetDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.status_page.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StatusPageRecord
     */
    public StatusPageRecord() {
        super(StatusPage.STATUS_PAGE);
    }

    /**
     * Create a detached, initialised StatusPageRecord
     */
    public StatusPageRecord(Long id, String title, String slug, Boolean enabled, MonitorID[] monitors, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        super(StatusPage.STATUS_PAGE);

        setId(id);
        setTitle(title);
        setSlug(slug);
        setEnabled(enabled);
        setMonitors(monitors);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised StatusPageRecord
     */
    public StatusPageRecord(com.kuvaszuptime.kuvasz.jooq.tables.pojos.StatusPage value) {
        super(StatusPage.STATUS_PAGE);

        if (value != null) {
            setId(value.getId());
            setTitle(value.getTitle());
            setSlug(value.getSlug());
            setEnabled(value.getEnabled());
            setMonitors(value.getMonitors());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetTouchedOnNotNull();
        }
    }
}
