/*
 * This file is generated by jOOQ.
 */
package com.kuvaszuptime.kuvasz.jooq.tables.records;


import com.kuvaszuptime.kuvasz.jooq.MetricsHistoryMonitorRecord;
import com.kuvaszuptime.kuvasz.jooq.SchedulableMonitorRecord;
import com.kuvaszuptime.kuvasz.jooq.tables.TcpMonitor;
import com.kuvaszuptime.kuvasz.models.handlers.IntegrationID;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TcpMonitorRecord extends UpdatableRecordImpl<TcpMonitorRecord> implements SchedulableMonitorRecord, MetricsHistoryMonitorRecord {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>kuvasz.tcp_monitor.id</code>.
     */
    public TcpMonitorRecord setId(Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.tcp_monitor.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>kuvasz.tcp_monitor.name</code>.
     */
    public TcpMonitorRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.tcp_monitor.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>kuvasz.tcp_monitor.host</code>.
     */
    public TcpMonitorRecord setHost(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.tcp_monitor.host</code>.
     */
    public String getHost() {
        return (String) get(2);
    }

    /**
     * Setter for <code>kuvasz.tcp_monitor.port</code>.
     */
    public TcpMonitorRecord setPort(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.tcp_monitor.port</code>.
     */
    public Integer getPort() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>kuvasz.tcp_monitor.uptime_check_interval</code>.
     */
    public TcpMonitorRecord setUptimeCheckInterval(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.tcp_monitor.uptime_check_interval</code>.
     */
    public Integer getUptimeCheckInterval() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>kuvasz.tcp_monitor.timeout_ms</code>.
     */
    public TcpMonitorRecord setTimeoutMs(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.tcp_monitor.timeout_ms</code>.
     */
    public Integer getTimeoutMs() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>kuvasz.tcp_monitor.latency_threshold_ms</code>.
     */
    public TcpMonitorRecord setLatencyThresholdMs(Integer value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.tcp_monitor.latency_threshold_ms</code>.
     */
    public Integer getLatencyThresholdMs() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>kuvasz.tcp_monitor.failure_count_threshold</code>.
     */
    public TcpMonitorRecord setFailureCountThreshold(Long value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.tcp_monitor.failure_count_threshold</code>.
     */
    public Long getFailureCountThreshold() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>kuvasz.tcp_monitor.enabled</code>.
     */
    public TcpMonitorRecord setEnabled(Boolean value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.tcp_monitor.enabled</code>.
     */
    public Boolean getEnabled() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>kuvasz.tcp_monitor.metrics_history_enabled</code>.
     */
    public TcpMonitorRecord setMetricsHistoryEnabled(Boolean value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.tcp_monitor.metrics_history_enabled</code>.
     */
    public Boolean getMetricsHistoryEnabled() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>kuvasz.tcp_monitor.integrations</code>.
     */
    public TcpMonitorRecord setIntegrations(IntegrationID[] value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.tcp_monitor.integrations</code>.
     */
    public IntegrationID[] getIntegrations() {
        return (IntegrationID[]) get(10);
    }

    /**
     * Setter for <code>kuvasz.tcp_monitor.created_at</code>.
     */
    public TcpMonitorRecord setCreatedAt(OffsetDateTime value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.tcp_monitor.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(11);
    }

    /**
     * Setter for <code>kuvasz.tcp_monitor.updated_at</code>.
     */
    public TcpMonitorRecord setUpdatedAt(OffsetDateTime value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>kuvasz.tcp_monitor.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TcpMonitorRecord
     */
    public TcpMonitorRecord() {
        super(TcpMonitor.TCP_MONITOR);
    }

    /**
     * Create a detached, initialised TcpMonitorRecord
     */
    public TcpMonitorRecord(Long id, String name, String host, Integer port, Integer uptimeCheckInterval, Integer timeoutMs, Integer latencyThresholdMs, Long failureCountThreshold, Boolean enabled, Boolean metricsHistoryEnabled, IntegrationID[] integrations, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        super(TcpMonitor.TCP_MONITOR);

        setId(id);
        setName(name);
        setHost(host);
        setPort(port);
        setUptimeCheckInterval(uptimeCheckInterval);
        setTimeoutMs(timeoutMs);
        setLatencyThresholdMs(latencyThresholdMs);
        setFailureCountThreshold(failureCountThreshold);
        setEnabled(enabled);
        setMetricsHistoryEnabled(metricsHistoryEnabled);
        setIntegrations(integrations);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised TcpMonitorRecord
     */
    public TcpMonitorRecord(com.kuvaszuptime.kuvasz.jooq.tables.pojos.TcpMonitor value) {
        super(TcpMonitor.TCP_MONITOR);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setHost(value.getHost());
            setPort(value.getPort());
            setUptimeCheckInterval(value.getUptimeCheckInterval());
            setTimeoutMs(value.getTimeoutMs());
            setLatencyThresholdMs(value.getLatencyThresholdMs());
            setFailureCountThreshold(value.getFailureCountThreshold());
            setEnabled(value.getEnabled());
            setMetricsHistoryEnabled(value.getMetricsHistoryEnabled());
            setIntegrations(value.getIntegrations());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetTouchedOnNotNull();
        }
    }
}
