/*
 * This file is generated by jOOQ.
 */
package com.kuvaszuptime.kuvasz.jooq;


import com.kuvaszuptime.kuvasz.jooq.tables.HttpLatencyLog;
import com.kuvaszuptime.kuvasz.jooq.tables.HttpMonitor;
import com.kuvaszuptime.kuvasz.jooq.tables.HttpUptimeEvent;
import com.kuvaszuptime.kuvasz.jooq.tables.SslEvent;
import com.kuvaszuptime.kuvasz.jooq.tables.records.HttpLatencyLogRecord;
import com.kuvaszuptime.kuvasz.jooq.tables.records.HttpMonitorRecord;
import com.kuvaszuptime.kuvasz.jooq.tables.records.HttpUptimeEventRecord;
import com.kuvaszuptime.kuvasz.jooq.tables.records.SslEventRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.QOM.ForeignKeyRule;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * kuvasz.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<HttpLatencyLogRecord> LATENCY_LOG_PKEY = Internal.createUniqueKey(HttpLatencyLog.HTTP_LATENCY_LOG, DSL.name("latency_log_pkey"), new TableField[] { HttpLatencyLog.HTTP_LATENCY_LOG.ID }, true);
    public static final UniqueKey<HttpMonitorRecord> MONITOR_PKEY = Internal.createUniqueKey(HttpMonitor.HTTP_MONITOR, DSL.name("monitor_pkey"), new TableField[] { HttpMonitor.HTTP_MONITOR.ID }, true);
    public static final UniqueKey<HttpMonitorRecord> UNIQUE_MONITOR_NAME = Internal.createUniqueKey(HttpMonitor.HTTP_MONITOR, DSL.name("unique_monitor_name"), new TableField[] { HttpMonitor.HTTP_MONITOR.NAME }, true);
    public static final UniqueKey<HttpUptimeEventRecord> UPTIME_EVENT_KEY = Internal.createUniqueKey(HttpUptimeEvent.HTTP_UPTIME_EVENT, DSL.name("uptime_event_key"), new TableField[] { HttpUptimeEvent.HTTP_UPTIME_EVENT.MONITOR_ID, HttpUptimeEvent.HTTP_UPTIME_EVENT.STATUS, HttpUptimeEvent.HTTP_UPTIME_EVENT.ENDED_AT }, true);
    public static final UniqueKey<HttpUptimeEventRecord> UPTIME_EVENT_PKEY = Internal.createUniqueKey(HttpUptimeEvent.HTTP_UPTIME_EVENT, DSL.name("uptime_event_pkey"), new TableField[] { HttpUptimeEvent.HTTP_UPTIME_EVENT.ID }, true);
    public static final UniqueKey<SslEventRecord> SSL_EVENT_KEY = Internal.createUniqueKey(SslEvent.SSL_EVENT, DSL.name("ssl_event_key"), new TableField[] { SslEvent.SSL_EVENT.MONITOR_ID, SslEvent.SSL_EVENT.STATUS, SslEvent.SSL_EVENT.ENDED_AT }, true);
    public static final UniqueKey<SslEventRecord> SSL_EVENT_PKEY = Internal.createUniqueKey(SslEvent.SSL_EVENT, DSL.name("ssl_event_pkey"), new TableField[] { SslEvent.SSL_EVENT.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<HttpLatencyLogRecord, HttpMonitorRecord> HTTP_LATENCY_LOG__LATENCY_LOG_MONITOR_ID_FKEY = Internal.createForeignKey(HttpLatencyLog.HTTP_LATENCY_LOG, DSL.name("latency_log_monitor_id_fkey"), new TableField[] { HttpLatencyLog.HTTP_LATENCY_LOG.MONITOR_ID }, Keys.MONITOR_PKEY, new TableField[] { HttpMonitor.HTTP_MONITOR.ID }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<HttpUptimeEventRecord, HttpMonitorRecord> HTTP_UPTIME_EVENT__UPTIME_EVENT_MONITOR_ID_FKEY = Internal.createForeignKey(HttpUptimeEvent.HTTP_UPTIME_EVENT, DSL.name("uptime_event_monitor_id_fkey"), new TableField[] { HttpUptimeEvent.HTTP_UPTIME_EVENT.MONITOR_ID }, Keys.MONITOR_PKEY, new TableField[] { HttpMonitor.HTTP_MONITOR.ID }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<SslEventRecord, HttpMonitorRecord> SSL_EVENT__SSL_EVENT_MONITOR_ID_FKEY = Internal.createForeignKey(SslEvent.SSL_EVENT, DSL.name("ssl_event_monitor_id_fkey"), new TableField[] { SslEvent.SSL_EVENT.MONITOR_ID }, Keys.MONITOR_PKEY, new TableField[] { HttpMonitor.HTTP_MONITOR.ID }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION);
}
