/*
 * This file is generated by jOOQ.
 */
package com.kuvaszuptime.kuvasz.jooq;


import com.kuvaszuptime.kuvasz.jooq.tables.HttpLatencyLog;
import com.kuvaszuptime.kuvasz.jooq.tables.HttpMonitor;
import com.kuvaszuptime.kuvasz.jooq.tables.HttpUptimeEvent;
import com.kuvaszuptime.kuvasz.jooq.tables.IcmpMetricsLog;
import com.kuvaszuptime.kuvasz.jooq.tables.IcmpMonitor;
import com.kuvaszuptime.kuvasz.jooq.tables.IcmpUptimeEvent;
import com.kuvaszuptime.kuvasz.jooq.tables.MaintenanceWindow;
import com.kuvaszuptime.kuvasz.jooq.tables.PendingFailure;
import com.kuvaszuptime.kuvasz.jooq.tables.PushMonitor;
import com.kuvaszuptime.kuvasz.jooq.tables.PushUptimeEvent;
import com.kuvaszuptime.kuvasz.jooq.tables.SslEvent;
import com.kuvaszuptime.kuvasz.jooq.tables.StatusPage;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Kuvasz extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>kuvasz</code>
     */
    public static final Kuvasz KUVASZ = new Kuvasz();

    /**
     * The table <code>kuvasz.http_latency_log</code>.
     */
    public final HttpLatencyLog HTTP_LATENCY_LOG = HttpLatencyLog.HTTP_LATENCY_LOG;

    /**
     * The table <code>kuvasz.http_monitor</code>.
     */
    public final HttpMonitor HTTP_MONITOR = HttpMonitor.HTTP_MONITOR;

    /**
     * The table <code>kuvasz.http_uptime_event</code>.
     */
    public final HttpUptimeEvent HTTP_UPTIME_EVENT = HttpUptimeEvent.HTTP_UPTIME_EVENT;

    /**
     * The table <code>kuvasz.icmp_metrics_log</code>.
     */
    public final IcmpMetricsLog ICMP_METRICS_LOG = IcmpMetricsLog.ICMP_METRICS_LOG;

    /**
     * The table <code>kuvasz.icmp_monitor</code>.
     */
    public final IcmpMonitor ICMP_MONITOR = IcmpMonitor.ICMP_MONITOR;

    /**
     * The table <code>kuvasz.icmp_uptime_event</code>.
     */
    public final IcmpUptimeEvent ICMP_UPTIME_EVENT = IcmpUptimeEvent.ICMP_UPTIME_EVENT;

    /**
     * The table <code>kuvasz.maintenance_window</code>.
     */
    public final MaintenanceWindow MAINTENANCE_WINDOW = MaintenanceWindow.MAINTENANCE_WINDOW;

    /**
     * The table <code>kuvasz.pending_failure</code>.
     */
    public final PendingFailure PENDING_FAILURE = PendingFailure.PENDING_FAILURE;

    /**
     * The table <code>kuvasz.push_monitor</code>.
     */
    public final PushMonitor PUSH_MONITOR = PushMonitor.PUSH_MONITOR;

    /**
     * The table <code>kuvasz.push_uptime_event</code>.
     */
    public final PushUptimeEvent PUSH_UPTIME_EVENT = PushUptimeEvent.PUSH_UPTIME_EVENT;

    /**
     * The table <code>kuvasz.ssl_event</code>.
     */
    public final SslEvent SSL_EVENT = SslEvent.SSL_EVENT;

    /**
     * The table <code>kuvasz.status_page</code>.
     */
    public final StatusPage STATUS_PAGE = StatusPage.STATUS_PAGE;

    /**
     * No further instances allowed
     */
    private Kuvasz() {
        super(DSL.name("kuvasz"), null, DSL.comment(""));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.asList(
            Sequences.LATENCY_LOG_ID_SEQ,
            Sequences.MONITOR_ID_SEQ,
            Sequences.UPTIME_EVENT_ID_SEQ
        );
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            HttpLatencyLog.HTTP_LATENCY_LOG,
            HttpMonitor.HTTP_MONITOR,
            HttpUptimeEvent.HTTP_UPTIME_EVENT,
            IcmpMetricsLog.ICMP_METRICS_LOG,
            IcmpMonitor.ICMP_MONITOR,
            IcmpUptimeEvent.ICMP_UPTIME_EVENT,
            MaintenanceWindow.MAINTENANCE_WINDOW,
            PendingFailure.PENDING_FAILURE,
            PushMonitor.PUSH_MONITOR,
            PushUptimeEvent.PUSH_UPTIME_EVENT,
            SslEvent.SSL_EVENT,
            StatusPage.STATUS_PAGE
        );
    }
}
