/*
 * This file is generated by jOOQ.
 */
package com.kuvaszuptime.kuvasz.jooq;


import org.jooq.Sequence;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in kuvasz.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Sequences {

    /**
     * The sequence <code>kuvasz.latency_log_id_seq</code>
     */
    public static final Sequence<Long> LATENCY_LOG_ID_SEQ = Internal.createSequence("latency_log_id_seq", Kuvasz.KUVASZ, DSL.comment(""), SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>kuvasz.monitor_id_seq</code>
     */
    public static final Sequence<Long> MONITOR_ID_SEQ = Internal.createSequence("monitor_id_seq", Kuvasz.KUVASZ, DSL.comment(""), SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>kuvasz.uptime_event_id_seq</code>
     */
    public static final Sequence<Long> UPTIME_EVENT_ID_SEQ = Internal.createSequence("uptime_event_id_seq", Kuvasz.KUVASZ, DSL.comment(""), SQLDataType.BIGINT.nullable(false), null, null, null, null, false, null);
}
