/*
 * This file is generated by jOOQ.
 */
package com.kuvaszuptime.kuvasz.jooq.tables;


import com.kuvaszuptime.kuvasz.jooq.Keys;
import com.kuvaszuptime.kuvasz.jooq.Kuvasz;
import com.kuvaszuptime.kuvasz.jooq.tables.DnsMonitor.DnsMonitorPath;
import com.kuvaszuptime.kuvasz.jooq.tables.records.DnsResolutionSnapshotRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.jackson3.extensions.converters.JSONBtoJacksonConverter;

import tools.jackson.databind.JsonNode;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DnsResolutionSnapshot extends TableImpl<DnsResolutionSnapshotRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>kuvasz.dns_resolution_snapshot</code>
     */
    public static final DnsResolutionSnapshot DNS_RESOLUTION_SNAPSHOT = new DnsResolutionSnapshot();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DnsResolutionSnapshotRecord> getRecordType() {
        return DnsResolutionSnapshotRecord.class;
    }

    /**
     * The column <code>kuvasz.dns_resolution_snapshot.monitor_id</code>.
     */
    public final TableField<DnsResolutionSnapshotRecord, Long> MONITOR_ID = createField(DSL.name("monitor_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>kuvasz.dns_resolution_snapshot.records</code>.
     */
    public final TableField<DnsResolutionSnapshotRecord, JsonNode> RECORDS = createField(DSL.name("records"), SQLDataType.JSONB.nullable(false), this, "", new JSONBtoJacksonConverter<JsonNode>(JsonNode.class));

    /**
     * The column <code>kuvasz.dns_resolution_snapshot.updated_at</code>.
     */
    public final TableField<DnsResolutionSnapshotRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private DnsResolutionSnapshot(Name alias, Table<DnsResolutionSnapshotRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private DnsResolutionSnapshot(Name alias, Table<DnsResolutionSnapshotRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>kuvasz.dns_resolution_snapshot</code> table
     * reference
     */
    public DnsResolutionSnapshot(String alias) {
        this(DSL.name(alias), DNS_RESOLUTION_SNAPSHOT);
    }

    /**
     * Create an aliased <code>kuvasz.dns_resolution_snapshot</code> table
     * reference
     */
    public DnsResolutionSnapshot(Name alias) {
        this(alias, DNS_RESOLUTION_SNAPSHOT);
    }

    /**
     * Create a <code>kuvasz.dns_resolution_snapshot</code> table reference
     */
    public DnsResolutionSnapshot() {
        this(DSL.name("dns_resolution_snapshot"), null);
    }

    public <O extends Record> DnsResolutionSnapshot(Table<O> path, ForeignKey<O, DnsResolutionSnapshotRecord> childPath, InverseForeignKey<O, DnsResolutionSnapshotRecord> parentPath) {
        super(path, childPath, parentPath, DNS_RESOLUTION_SNAPSHOT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class DnsResolutionSnapshotPath extends DnsResolutionSnapshot implements Path<DnsResolutionSnapshotRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> DnsResolutionSnapshotPath(Table<O> path, ForeignKey<O, DnsResolutionSnapshotRecord> childPath, InverseForeignKey<O, DnsResolutionSnapshotRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private DnsResolutionSnapshotPath(Name alias, Table<DnsResolutionSnapshotRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public DnsResolutionSnapshotPath as(String alias) {
            return new DnsResolutionSnapshotPath(DSL.name(alias), this);
        }

        @Override
        public DnsResolutionSnapshotPath as(Name alias) {
            return new DnsResolutionSnapshotPath(alias, this);
        }

        @Override
        public DnsResolutionSnapshotPath as(Table<?> alias) {
            return new DnsResolutionSnapshotPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Kuvasz.KUVASZ;
    }

    @Override
    public UniqueKey<DnsResolutionSnapshotRecord> getPrimaryKey() {
        return Keys.DNS_RESOLUTION_SNAPSHOT_PKEY;
    }

    @Override
    public List<ForeignKey<DnsResolutionSnapshotRecord, ?>> getReferences() {
        return Arrays.asList(Keys.DNS_RESOLUTION_SNAPSHOT__DNS_RESOLUTION_SNAPSHOT_MONITOR_ID_FKEY);
    }

    private transient DnsMonitorPath _dnsMonitor;

    /**
     * Get the implicit join path to the <code>kuvasz.dns_monitor</code> table.
     */
    public DnsMonitorPath dnsMonitor() {
        if (_dnsMonitor == null)
            _dnsMonitor = new DnsMonitorPath(this, Keys.DNS_RESOLUTION_SNAPSHOT__DNS_RESOLUTION_SNAPSHOT_MONITOR_ID_FKEY, null);

        return _dnsMonitor;
    }

    @Override
    public DnsResolutionSnapshot as(String alias) {
        return new DnsResolutionSnapshot(DSL.name(alias), this);
    }

    @Override
    public DnsResolutionSnapshot as(Name alias) {
        return new DnsResolutionSnapshot(alias, this);
    }

    @Override
    public DnsResolutionSnapshot as(Table<?> alias) {
        return new DnsResolutionSnapshot(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public DnsResolutionSnapshot rename(String name) {
        return new DnsResolutionSnapshot(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DnsResolutionSnapshot rename(Name name) {
        return new DnsResolutionSnapshot(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public DnsResolutionSnapshot rename(Table<?> name) {
        return new DnsResolutionSnapshot(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DnsResolutionSnapshot where(Condition condition) {
        return new DnsResolutionSnapshot(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DnsResolutionSnapshot where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DnsResolutionSnapshot where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DnsResolutionSnapshot where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DnsResolutionSnapshot where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DnsResolutionSnapshot where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DnsResolutionSnapshot where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DnsResolutionSnapshot where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DnsResolutionSnapshot whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DnsResolutionSnapshot whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
