/*
 * This file is generated by jOOQ.
 */
package com.kuvaszuptime.kuvasz.jooq.tables;


import com.kuvaszuptime.kuvasz.jooq.Indexes;
import com.kuvaszuptime.kuvasz.jooq.Keys;
import com.kuvaszuptime.kuvasz.jooq.Kuvasz;
import com.kuvaszuptime.kuvasz.jooq.tables.DockerMonitor.DockerMonitorPath;
import com.kuvaszuptime.kuvasz.jooq.tables.records.DockerMetricsLogRecord;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DockerMetricsLog extends TableImpl<DockerMetricsLogRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>kuvasz.docker_metrics_log</code>
     */
    public static final DockerMetricsLog DOCKER_METRICS_LOG = new DockerMetricsLog();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DockerMetricsLogRecord> getRecordType() {
        return DockerMetricsLogRecord.class;
    }

    /**
     * The column <code>kuvasz.docker_metrics_log.id</code>.
     */
    public final TableField<DockerMetricsLogRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>kuvasz.docker_metrics_log.monitor_id</code>.
     */
    public final TableField<DockerMetricsLogRecord, Long> MONITOR_ID = createField(DSL.name("monitor_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>kuvasz.docker_metrics_log.latency_ms</code>.
     */
    public final TableField<DockerMetricsLogRecord, Integer> LATENCY_MS = createField(DSL.name("latency_ms"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>kuvasz.docker_metrics_log.cpu_usage_percent</code>.
     */
    public final TableField<DockerMetricsLogRecord, BigDecimal> CPU_USAGE_PERCENT = createField(DSL.name("cpu_usage_percent"), SQLDataType.NUMERIC(7, 2), this, "");

    /**
     * The column <code>kuvasz.docker_metrics_log.memory_usage_bytes</code>.
     */
    public final TableField<DockerMetricsLogRecord, Long> MEMORY_USAGE_BYTES = createField(DSL.name("memory_usage_bytes"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>kuvasz.docker_metrics_log.memory_limit_bytes</code>.
     */
    public final TableField<DockerMetricsLogRecord, Long> MEMORY_LIMIT_BYTES = createField(DSL.name("memory_limit_bytes"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>kuvasz.docker_metrics_log.created_at</code>.
     */
    public final TableField<DockerMetricsLogRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private DockerMetricsLog(Name alias, Table<DockerMetricsLogRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private DockerMetricsLog(Name alias, Table<DockerMetricsLogRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>kuvasz.docker_metrics_log</code> table reference
     */
    public DockerMetricsLog(String alias) {
        this(DSL.name(alias), DOCKER_METRICS_LOG);
    }

    /**
     * Create an aliased <code>kuvasz.docker_metrics_log</code> table reference
     */
    public DockerMetricsLog(Name alias) {
        this(alias, DOCKER_METRICS_LOG);
    }

    /**
     * Create a <code>kuvasz.docker_metrics_log</code> table reference
     */
    public DockerMetricsLog() {
        this(DSL.name("docker_metrics_log"), null);
    }

    public <O extends Record> DockerMetricsLog(Table<O> path, ForeignKey<O, DockerMetricsLogRecord> childPath, InverseForeignKey<O, DockerMetricsLogRecord> parentPath) {
        super(path, childPath, parentPath, DOCKER_METRICS_LOG);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class DockerMetricsLogPath extends DockerMetricsLog implements Path<DockerMetricsLogRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> DockerMetricsLogPath(Table<O> path, ForeignKey<O, DockerMetricsLogRecord> childPath, InverseForeignKey<O, DockerMetricsLogRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private DockerMetricsLogPath(Name alias, Table<DockerMetricsLogRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public DockerMetricsLogPath as(String alias) {
            return new DockerMetricsLogPath(DSL.name(alias), this);
        }

        @Override
        public DockerMetricsLogPath as(Name alias) {
            return new DockerMetricsLogPath(alias, this);
        }

        @Override
        public DockerMetricsLogPath as(Table<?> alias) {
            return new DockerMetricsLogPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Kuvasz.KUVASZ;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.DOCKER_METRICS_LOG_CREATED_AT_IDX, Indexes.DOCKER_METRICS_LOG_MONITOR_ID_IDX);
    }

    @Override
    public Identity<DockerMetricsLogRecord, Long> getIdentity() {
        return (Identity<DockerMetricsLogRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<DockerMetricsLogRecord> getPrimaryKey() {
        return Keys.DOCKER_METRICS_LOG_PKEY;
    }

    @Override
    public List<ForeignKey<DockerMetricsLogRecord, ?>> getReferences() {
        return Arrays.asList(Keys.DOCKER_METRICS_LOG__DOCKER_METRICS_LOG_MONITOR_ID_FKEY);
    }

    private transient DockerMonitorPath _dockerMonitor;

    /**
     * Get the implicit join path to the <code>kuvasz.docker_monitor</code>
     * table.
     */
    public DockerMonitorPath dockerMonitor() {
        if (_dockerMonitor == null)
            _dockerMonitor = new DockerMonitorPath(this, Keys.DOCKER_METRICS_LOG__DOCKER_METRICS_LOG_MONITOR_ID_FKEY, null);

        return _dockerMonitor;
    }

    @Override
    public DockerMetricsLog as(String alias) {
        return new DockerMetricsLog(DSL.name(alias), this);
    }

    @Override
    public DockerMetricsLog as(Name alias) {
        return new DockerMetricsLog(alias, this);
    }

    @Override
    public DockerMetricsLog as(Table<?> alias) {
        return new DockerMetricsLog(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public DockerMetricsLog rename(String name) {
        return new DockerMetricsLog(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DockerMetricsLog rename(Name name) {
        return new DockerMetricsLog(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public DockerMetricsLog rename(Table<?> name) {
        return new DockerMetricsLog(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DockerMetricsLog where(Condition condition) {
        return new DockerMetricsLog(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DockerMetricsLog where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DockerMetricsLog where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DockerMetricsLog where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DockerMetricsLog where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DockerMetricsLog where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DockerMetricsLog where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DockerMetricsLog where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DockerMetricsLog whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DockerMetricsLog whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
