/*
 * This file is generated by jOOQ.
 */
package com.kuvaszuptime.kuvasz.jooq.tables;


import com.kuvaszuptime.kuvasz.jooq.Indexes;
import com.kuvaszuptime.kuvasz.jooq.Keys;
import com.kuvaszuptime.kuvasz.jooq.Kuvasz;
import com.kuvaszuptime.kuvasz.jooq.enums.UptimeStatus;
import com.kuvaszuptime.kuvasz.jooq.tables.DockerMonitor.DockerMonitorPath;
import com.kuvaszuptime.kuvasz.jooq.tables.records.DockerUptimeEventRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DockerUptimeEvent extends TableImpl<DockerUptimeEventRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>kuvasz.docker_uptime_event</code>
     */
    public static final DockerUptimeEvent DOCKER_UPTIME_EVENT = new DockerUptimeEvent();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DockerUptimeEventRecord> getRecordType() {
        return DockerUptimeEventRecord.class;
    }

    /**
     * The column <code>kuvasz.docker_uptime_event.id</code>.
     */
    public final TableField<DockerUptimeEventRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).generatedByDefaultAsIdentity(), this, "");

    /**
     * The column <code>kuvasz.docker_uptime_event.monitor_id</code>.
     */
    public final TableField<DockerUptimeEventRecord, Long> MONITOR_ID = createField(DSL.name("monitor_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>kuvasz.docker_uptime_event.status</code>.
     */
    public final TableField<DockerUptimeEventRecord, UptimeStatus> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(UptimeStatus.class), this, "");

    /**
     * The column <code>kuvasz.docker_uptime_event.error</code>.
     */
    public final TableField<DockerUptimeEventRecord, String> ERROR = createField(DSL.name("error"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>kuvasz.docker_uptime_event.started_at</code>.
     */
    public final TableField<DockerUptimeEventRecord, OffsetDateTime> STARTED_AT = createField(DSL.name("started_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>kuvasz.docker_uptime_event.ended_at</code>.
     */
    public final TableField<DockerUptimeEventRecord, OffsetDateTime> ENDED_AT = createField(DSL.name("ended_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>kuvasz.docker_uptime_event.updated_at</code>.
     */
    public final TableField<DockerUptimeEventRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>kuvasz.docker_uptime_event.image</code>.
     */
    public final TableField<DockerUptimeEventRecord, String> IMAGE = createField(DSL.name("image"), SQLDataType.CLOB, this, "");

    private DockerUptimeEvent(Name alias, Table<DockerUptimeEventRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private DockerUptimeEvent(Name alias, Table<DockerUptimeEventRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>kuvasz.docker_uptime_event</code> table reference
     */
    public DockerUptimeEvent(String alias) {
        this(DSL.name(alias), DOCKER_UPTIME_EVENT);
    }

    /**
     * Create an aliased <code>kuvasz.docker_uptime_event</code> table reference
     */
    public DockerUptimeEvent(Name alias) {
        this(alias, DOCKER_UPTIME_EVENT);
    }

    /**
     * Create a <code>kuvasz.docker_uptime_event</code> table reference
     */
    public DockerUptimeEvent() {
        this(DSL.name("docker_uptime_event"), null);
    }

    public <O extends Record> DockerUptimeEvent(Table<O> path, ForeignKey<O, DockerUptimeEventRecord> childPath, InverseForeignKey<O, DockerUptimeEventRecord> parentPath) {
        super(path, childPath, parentPath, DOCKER_UPTIME_EVENT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class DockerUptimeEventPath extends DockerUptimeEvent implements Path<DockerUptimeEventRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> DockerUptimeEventPath(Table<O> path, ForeignKey<O, DockerUptimeEventRecord> childPath, InverseForeignKey<O, DockerUptimeEventRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private DockerUptimeEventPath(Name alias, Table<DockerUptimeEventRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public DockerUptimeEventPath as(String alias) {
            return new DockerUptimeEventPath(DSL.name(alias), this);
        }

        @Override
        public DockerUptimeEventPath as(Name alias) {
            return new DockerUptimeEventPath(alias, this);
        }

        @Override
        public DockerUptimeEventPath as(Table<?> alias) {
            return new DockerUptimeEventPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Kuvasz.KUVASZ;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.DOCKER_UPTIME_EVENT_ENDED_AT_IDX, Indexes.DOCKER_UPTIME_EVENT_MONITOR_IDX);
    }

    @Override
    public Identity<DockerUptimeEventRecord, Long> getIdentity() {
        return (Identity<DockerUptimeEventRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<DockerUptimeEventRecord> getPrimaryKey() {
        return Keys.DOCKER_UPTIME_EVENT_PKEY;
    }

    @Override
    public List<UniqueKey<DockerUptimeEventRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.DOCKER_UPTIME_EVENT_KEY);
    }

    @Override
    public List<ForeignKey<DockerUptimeEventRecord, ?>> getReferences() {
        return Arrays.asList(Keys.DOCKER_UPTIME_EVENT__DOCKER_UPTIME_EVENT_MONITOR_ID_FKEY);
    }

    private transient DockerMonitorPath _dockerMonitor;

    /**
     * Get the implicit join path to the <code>kuvasz.docker_monitor</code>
     * table.
     */
    public DockerMonitorPath dockerMonitor() {
        if (_dockerMonitor == null)
            _dockerMonitor = new DockerMonitorPath(this, Keys.DOCKER_UPTIME_EVENT__DOCKER_UPTIME_EVENT_MONITOR_ID_FKEY, null);

        return _dockerMonitor;
    }

    @Override
    public DockerUptimeEvent as(String alias) {
        return new DockerUptimeEvent(DSL.name(alias), this);
    }

    @Override
    public DockerUptimeEvent as(Name alias) {
        return new DockerUptimeEvent(alias, this);
    }

    @Override
    public DockerUptimeEvent as(Table<?> alias) {
        return new DockerUptimeEvent(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public DockerUptimeEvent rename(String name) {
        return new DockerUptimeEvent(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DockerUptimeEvent rename(Name name) {
        return new DockerUptimeEvent(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public DockerUptimeEvent rename(Table<?> name) {
        return new DockerUptimeEvent(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DockerUptimeEvent where(Condition condition) {
        return new DockerUptimeEvent(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DockerUptimeEvent where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DockerUptimeEvent where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DockerUptimeEvent where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DockerUptimeEvent where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DockerUptimeEvent where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DockerUptimeEvent where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DockerUptimeEvent where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DockerUptimeEvent whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DockerUptimeEvent whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
