/*
 * This file is generated by jOOQ.
 */
package com.kuvaszuptime.kuvasz.jooq.tables;


import com.fasterxml.jackson.databind.JsonNode;
import com.kuvaszuptime.kuvasz.jooq.Keys;
import com.kuvaszuptime.kuvasz.jooq.Kuvasz;
import com.kuvaszuptime.kuvasz.jooq.TextArrayToIntegrationIdArrayConverter;
import com.kuvaszuptime.kuvasz.jooq.enums.HttpMethod;
import com.kuvaszuptime.kuvasz.jooq.tables.HttpLatencyLog.HttpLatencyLogPath;
import com.kuvaszuptime.kuvasz.jooq.tables.HttpUptimeEvent.HttpUptimeEventPath;
import com.kuvaszuptime.kuvasz.jooq.tables.SslEvent.SslEventPath;
import com.kuvaszuptime.kuvasz.jooq.tables.records.HttpMonitorRecord;
import com.kuvaszuptime.kuvasz.models.handlers.IntegrationID;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.jackson.extensions.converters.JSONBtoJacksonConverter;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class HttpMonitor extends TableImpl<HttpMonitorRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>kuvasz.http_monitor</code>
     */
    public static final HttpMonitor HTTP_MONITOR = new HttpMonitor();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HttpMonitorRecord> getRecordType() {
        return HttpMonitorRecord.class;
    }

    /**
     * The column <code>kuvasz.http_monitor.id</code>.
     */
    public final TableField<HttpMonitorRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>kuvasz.http_monitor.name</code>. Monitor's name
     */
    public final TableField<HttpMonitorRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "Monitor's name");

    /**
     * The column <code>kuvasz.http_monitor.url</code>. URL to check
     */
    public final TableField<HttpMonitorRecord, String> URL = createField(DSL.name("url"), SQLDataType.CLOB.nullable(false), this, "URL to check");

    /**
     * The column <code>kuvasz.http_monitor.uptime_check_interval</code>. Uptime
     * checking interval in seconds
     */
    public final TableField<HttpMonitorRecord, Integer> UPTIME_CHECK_INTERVAL = createField(DSL.name("uptime_check_interval"), SQLDataType.INTEGER.nullable(false), this, "Uptime checking interval in seconds");

    /**
     * The column <code>kuvasz.http_monitor.enabled</code>. Flag to toggle the
     * monitor
     */
    public final TableField<HttpMonitorRecord, Boolean> ENABLED = createField(DSL.name("enabled"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "Flag to toggle the monitor");

    /**
     * The column <code>kuvasz.http_monitor.created_at</code>.
     */
    public final TableField<HttpMonitorRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>kuvasz.http_monitor.updated_at</code>.
     */
    public final TableField<HttpMonitorRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>kuvasz.http_monitor.ssl_check_enabled</code>.
     */
    public final TableField<HttpMonitorRecord, Boolean> SSL_CHECK_ENABLED = createField(DSL.name("ssl_check_enabled"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>kuvasz.http_monitor.latency_history_enabled</code>.
     */
    public final TableField<HttpMonitorRecord, Boolean> LATENCY_HISTORY_ENABLED = createField(DSL.name("latency_history_enabled"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>kuvasz.http_monitor.follow_redirects</code>.
     */
    public final TableField<HttpMonitorRecord, Boolean> FOLLOW_REDIRECTS = createField(DSL.name("follow_redirects"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>kuvasz.http_monitor.force_no_cache</code>.
     */
    public final TableField<HttpMonitorRecord, Boolean> FORCE_NO_CACHE = createField(DSL.name("force_no_cache"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>kuvasz.http_monitor.request_method</code>.
     */
    public final TableField<HttpMonitorRecord, HttpMethod> REQUEST_METHOD = createField(DSL.name("request_method"), SQLDataType.VARCHAR.nullable(false).defaultValue(DSL.field(DSL.raw("'GET'::kuvasz.http_method"), SQLDataType.VARCHAR)).asEnumDataType(HttpMethod.class), this, "");

    /**
     * The column <code>kuvasz.http_monitor.ssl_expiry_threshold</code>.
     */
    public final TableField<HttpMonitorRecord, Integer> SSL_EXPIRY_THRESHOLD = createField(DSL.name("ssl_expiry_threshold"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("30"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>kuvasz.http_monitor.integrations</code>.
     */
    public final TableField<HttpMonitorRecord, IntegrationID[]> INTEGRATIONS = createField(DSL.name("integrations"), SQLDataType.CLOB.array().nullable(false).defaultValue(DSL.field(DSL.raw("ARRAY[]::text[]"), SQLDataType.CLOB.array())), this, "", new TextArrayToIntegrationIdArrayConverter());

    /**
     * The column <code>kuvasz.http_monitor.expected_status_codes</code>.
     */
    public final TableField<HttpMonitorRecord, Integer[]> EXPECTED_STATUS_CODES = createField(DSL.name("expected_status_codes"), SQLDataType.INTEGER.array().nullable(false).defaultValue(DSL.field(DSL.raw("ARRAY[]::integer[]"), SQLDataType.INTEGER.array())), this, "");

    /**
     * The column
     * <code>kuvasz.http_monitor.response_time_threshold_millis</code>.
     */
    public final TableField<HttpMonitorRecord, Integer> RESPONSE_TIME_THRESHOLD_MILLIS = createField(DSL.name("response_time_threshold_millis"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>kuvasz.http_monitor.expected_keyword</code>.
     */
    public final TableField<HttpMonitorRecord, String> EXPECTED_KEYWORD = createField(DSL.name("expected_keyword"), SQLDataType.CLOB, this, "");

    /**
     * The column
     * <code>kuvasz.http_monitor.expected_keyword_case_sensitive</code>.
     */
    public final TableField<HttpMonitorRecord, Boolean> EXPECTED_KEYWORD_CASE_SENSITIVE = createField(DSL.name("expected_keyword_case_sensitive"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>kuvasz.http_monitor.expected_keyword_negated</code>.
     */
    public final TableField<HttpMonitorRecord, Boolean> EXPECTED_KEYWORD_NEGATED = createField(DSL.name("expected_keyword_negated"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>kuvasz.http_monitor.request_headers</code>.
     */
    public final TableField<HttpMonitorRecord, JsonNode> REQUEST_HEADERS = createField(DSL.name("request_headers"), SQLDataType.JSONB.nullable(false).defaultValue(DSL.field(DSL.raw("'{}'::jsonb"), SQLDataType.JSONB)), this, "", new JSONBtoJacksonConverter<JsonNode>(JsonNode.class));

    /**
     * The column <code>kuvasz.http_monitor.expected_headers</code>.
     */
    public final TableField<HttpMonitorRecord, JsonNode> EXPECTED_HEADERS = createField(DSL.name("expected_headers"), SQLDataType.JSONB.nullable(false).defaultValue(DSL.field(DSL.raw("'{}'::jsonb"), SQLDataType.JSONB)), this, "", new JSONBtoJacksonConverter<JsonNode>(JsonNode.class));

    /**
     * The column <code>kuvasz.http_monitor.request_body</code>.
     */
    public final TableField<HttpMonitorRecord, String> REQUEST_BODY = createField(DSL.name("request_body"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>kuvasz.http_monitor.failure_count_threshold</code>.
     */
    public final TableField<HttpMonitorRecord, Long> FAILURE_COUNT_THRESHOLD = createField(DSL.name("failure_count_threshold"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>kuvasz.http_monitor.sensitive_url</code>.
     */
    public final TableField<HttpMonitorRecord, Boolean> SENSITIVE_URL = createField(DSL.name("sensitive_url"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    private HttpMonitor(Name alias, Table<HttpMonitorRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private HttpMonitor(Name alias, Table<HttpMonitorRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>kuvasz.http_monitor</code> table reference
     */
    public HttpMonitor(String alias) {
        this(DSL.name(alias), HTTP_MONITOR);
    }

    /**
     * Create an aliased <code>kuvasz.http_monitor</code> table reference
     */
    public HttpMonitor(Name alias) {
        this(alias, HTTP_MONITOR);
    }

    /**
     * Create a <code>kuvasz.http_monitor</code> table reference
     */
    public HttpMonitor() {
        this(DSL.name("http_monitor"), null);
    }

    public <O extends Record> HttpMonitor(Table<O> path, ForeignKey<O, HttpMonitorRecord> childPath, InverseForeignKey<O, HttpMonitorRecord> parentPath) {
        super(path, childPath, parentPath, HTTP_MONITOR);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class HttpMonitorPath extends HttpMonitor implements Path<HttpMonitorRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> HttpMonitorPath(Table<O> path, ForeignKey<O, HttpMonitorRecord> childPath, InverseForeignKey<O, HttpMonitorRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private HttpMonitorPath(Name alias, Table<HttpMonitorRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public HttpMonitorPath as(String alias) {
            return new HttpMonitorPath(DSL.name(alias), this);
        }

        @Override
        public HttpMonitorPath as(Name alias) {
            return new HttpMonitorPath(alias, this);
        }

        @Override
        public HttpMonitorPath as(Table<?> alias) {
            return new HttpMonitorPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Kuvasz.KUVASZ;
    }

    @Override
    public Identity<HttpMonitorRecord, Long> getIdentity() {
        return (Identity<HttpMonitorRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<HttpMonitorRecord> getPrimaryKey() {
        return Keys.MONITOR_PKEY;
    }

    @Override
    public List<UniqueKey<HttpMonitorRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UNIQUE_MONITOR_NAME);
    }

    private transient HttpLatencyLogPath _httpLatencyLog;

    /**
     * Get the implicit to-many join path to the
     * <code>kuvasz.http_latency_log</code> table
     */
    public HttpLatencyLogPath httpLatencyLog() {
        if (_httpLatencyLog == null)
            _httpLatencyLog = new HttpLatencyLogPath(this, null, Keys.HTTP_LATENCY_LOG__LATENCY_LOG_MONITOR_ID_FKEY.getInverseKey());

        return _httpLatencyLog;
    }

    private transient SslEventPath _sslEvent;

    /**
     * Get the implicit to-many join path to the <code>kuvasz.ssl_event</code>
     * table
     */
    public SslEventPath sslEvent() {
        if (_sslEvent == null)
            _sslEvent = new SslEventPath(this, null, Keys.SSL_EVENT__SSL_EVENT_MONITOR_ID_FKEY.getInverseKey());

        return _sslEvent;
    }

    private transient HttpUptimeEventPath _httpUptimeEvent;

    /**
     * Get the implicit to-many join path to the
     * <code>kuvasz.http_uptime_event</code> table
     */
    public HttpUptimeEventPath httpUptimeEvent() {
        if (_httpUptimeEvent == null)
            _httpUptimeEvent = new HttpUptimeEventPath(this, null, Keys.HTTP_UPTIME_EVENT__UPTIME_EVENT_MONITOR_ID_FKEY.getInverseKey());

        return _httpUptimeEvent;
    }

    @Override
    public HttpMonitor as(String alias) {
        return new HttpMonitor(DSL.name(alias), this);
    }

    @Override
    public HttpMonitor as(Name alias) {
        return new HttpMonitor(alias, this);
    }

    @Override
    public HttpMonitor as(Table<?> alias) {
        return new HttpMonitor(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public HttpMonitor rename(String name) {
        return new HttpMonitor(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public HttpMonitor rename(Name name) {
        return new HttpMonitor(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public HttpMonitor rename(Table<?> name) {
        return new HttpMonitor(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HttpMonitor where(Condition condition) {
        return new HttpMonitor(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HttpMonitor where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HttpMonitor where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HttpMonitor where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HttpMonitor where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HttpMonitor where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HttpMonitor where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HttpMonitor where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HttpMonitor whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HttpMonitor whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
