/*
 * This file is generated by jOOQ.
 */
package com.kuvaszuptime.kuvasz.jooq.tables;


import com.kuvaszuptime.kuvasz.jooq.Indexes;
import com.kuvaszuptime.kuvasz.jooq.Keys;
import com.kuvaszuptime.kuvasz.jooq.Kuvasz;
import com.kuvaszuptime.kuvasz.jooq.enums.UptimeStatus;
import com.kuvaszuptime.kuvasz.jooq.tables.HttpMonitor.HttpMonitorPath;
import com.kuvaszuptime.kuvasz.jooq.tables.records.HttpUptimeEventRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class HttpUptimeEvent extends TableImpl<HttpUptimeEventRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>kuvasz.http_uptime_event</code>
     */
    public static final HttpUptimeEvent HTTP_UPTIME_EVENT = new HttpUptimeEvent();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HttpUptimeEventRecord> getRecordType() {
        return HttpUptimeEventRecord.class;
    }

    /**
     * The column <code>kuvasz.http_uptime_event.id</code>.
     */
    public final TableField<HttpUptimeEventRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>kuvasz.http_uptime_event.monitor_id</code>.
     */
    public final TableField<HttpUptimeEventRecord, Long> MONITOR_ID = createField(DSL.name("monitor_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>kuvasz.http_uptime_event.status</code>. Status of the
     * event
     */
    public final TableField<HttpUptimeEventRecord, UptimeStatus> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(UptimeStatus.class), this, "Status of the event");

    /**
     * The column <code>kuvasz.http_uptime_event.error</code>.
     */
    public final TableField<HttpUptimeEventRecord, String> ERROR = createField(DSL.name("error"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>kuvasz.http_uptime_event.started_at</code>. The current
     * event started at
     */
    public final TableField<HttpUptimeEventRecord, OffsetDateTime> STARTED_AT = createField(DSL.name("started_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "The current event started at");

    /**
     * The column <code>kuvasz.http_uptime_event.ended_at</code>. The current
     * event ended at
     */
    public final TableField<HttpUptimeEventRecord, OffsetDateTime> ENDED_AT = createField(DSL.name("ended_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "The current event ended at");

    /**
     * The column <code>kuvasz.http_uptime_event.updated_at</code>.
     */
    public final TableField<HttpUptimeEventRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>kuvasz.http_uptime_event.failure_count</code>.
     */
    public final TableField<HttpUptimeEventRecord, Long> FAILURE_COUNT = createField(DSL.name("failure_count"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    private HttpUptimeEvent(Name alias, Table<HttpUptimeEventRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private HttpUptimeEvent(Name alias, Table<HttpUptimeEventRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>kuvasz.http_uptime_event</code> table reference
     */
    public HttpUptimeEvent(String alias) {
        this(DSL.name(alias), HTTP_UPTIME_EVENT);
    }

    /**
     * Create an aliased <code>kuvasz.http_uptime_event</code> table reference
     */
    public HttpUptimeEvent(Name alias) {
        this(alias, HTTP_UPTIME_EVENT);
    }

    /**
     * Create a <code>kuvasz.http_uptime_event</code> table reference
     */
    public HttpUptimeEvent() {
        this(DSL.name("http_uptime_event"), null);
    }

    public <O extends Record> HttpUptimeEvent(Table<O> path, ForeignKey<O, HttpUptimeEventRecord> childPath, InverseForeignKey<O, HttpUptimeEventRecord> parentPath) {
        super(path, childPath, parentPath, HTTP_UPTIME_EVENT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class HttpUptimeEventPath extends HttpUptimeEvent implements Path<HttpUptimeEventRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> HttpUptimeEventPath(Table<O> path, ForeignKey<O, HttpUptimeEventRecord> childPath, InverseForeignKey<O, HttpUptimeEventRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private HttpUptimeEventPath(Name alias, Table<HttpUptimeEventRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public HttpUptimeEventPath as(String alias) {
            return new HttpUptimeEventPath(DSL.name(alias), this);
        }

        @Override
        public HttpUptimeEventPath as(Name alias) {
            return new HttpUptimeEventPath(alias, this);
        }

        @Override
        public HttpUptimeEventPath as(Table<?> alias) {
            return new HttpUptimeEventPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Kuvasz.KUVASZ;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.UPTIME_EVENT_ENDED_AT_IDX, Indexes.UPTIME_EVENT_MONITOR_IDX);
    }

    @Override
    public Identity<HttpUptimeEventRecord, Long> getIdentity() {
        return (Identity<HttpUptimeEventRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<HttpUptimeEventRecord> getPrimaryKey() {
        return Keys.UPTIME_EVENT_PKEY;
    }

    @Override
    public List<UniqueKey<HttpUptimeEventRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UPTIME_EVENT_KEY);
    }

    @Override
    public List<ForeignKey<HttpUptimeEventRecord, ?>> getReferences() {
        return Arrays.asList(Keys.HTTP_UPTIME_EVENT__UPTIME_EVENT_MONITOR_ID_FKEY);
    }

    private transient HttpMonitorPath _httpMonitor;

    /**
     * Get the implicit join path to the <code>kuvasz.http_monitor</code> table.
     */
    public HttpMonitorPath httpMonitor() {
        if (_httpMonitor == null)
            _httpMonitor = new HttpMonitorPath(this, Keys.HTTP_UPTIME_EVENT__UPTIME_EVENT_MONITOR_ID_FKEY, null);

        return _httpMonitor;
    }

    @Override
    public HttpUptimeEvent as(String alias) {
        return new HttpUptimeEvent(DSL.name(alias), this);
    }

    @Override
    public HttpUptimeEvent as(Name alias) {
        return new HttpUptimeEvent(alias, this);
    }

    @Override
    public HttpUptimeEvent as(Table<?> alias) {
        return new HttpUptimeEvent(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public HttpUptimeEvent rename(String name) {
        return new HttpUptimeEvent(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public HttpUptimeEvent rename(Name name) {
        return new HttpUptimeEvent(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public HttpUptimeEvent rename(Table<?> name) {
        return new HttpUptimeEvent(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HttpUptimeEvent where(Condition condition) {
        return new HttpUptimeEvent(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HttpUptimeEvent where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HttpUptimeEvent where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HttpUptimeEvent where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HttpUptimeEvent where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HttpUptimeEvent where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HttpUptimeEvent where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public HttpUptimeEvent where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HttpUptimeEvent whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public HttpUptimeEvent whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
