/*
 * This file is generated by jOOQ.
 */
package com.kuvaszuptime.kuvasz.jooq.tables;


import com.kuvaszuptime.kuvasz.jooq.Indexes;
import com.kuvaszuptime.kuvasz.jooq.Keys;
import com.kuvaszuptime.kuvasz.jooq.Kuvasz;
import com.kuvaszuptime.kuvasz.jooq.enums.UptimeStatus;
import com.kuvaszuptime.kuvasz.jooq.tables.IcmpMonitor.IcmpMonitorPath;
import com.kuvaszuptime.kuvasz.jooq.tables.records.IcmpUptimeEventRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class IcmpUptimeEvent extends TableImpl<IcmpUptimeEventRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>kuvasz.icmp_uptime_event</code>
     */
    public static final IcmpUptimeEvent ICMP_UPTIME_EVENT = new IcmpUptimeEvent();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<IcmpUptimeEventRecord> getRecordType() {
        return IcmpUptimeEventRecord.class;
    }

    /**
     * The column <code>kuvasz.icmp_uptime_event.id</code>.
     */
    public final TableField<IcmpUptimeEventRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>kuvasz.icmp_uptime_event.monitor_id</code>.
     */
    public final TableField<IcmpUptimeEventRecord, Long> MONITOR_ID = createField(DSL.name("monitor_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>kuvasz.icmp_uptime_event.status</code>.
     */
    public final TableField<IcmpUptimeEventRecord, UptimeStatus> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(UptimeStatus.class), this, "");

    /**
     * The column <code>kuvasz.icmp_uptime_event.error</code>.
     */
    public final TableField<IcmpUptimeEventRecord, String> ERROR = createField(DSL.name("error"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>kuvasz.icmp_uptime_event.started_at</code>.
     */
    public final TableField<IcmpUptimeEventRecord, OffsetDateTime> STARTED_AT = createField(DSL.name("started_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>kuvasz.icmp_uptime_event.ended_at</code>.
     */
    public final TableField<IcmpUptimeEventRecord, OffsetDateTime> ENDED_AT = createField(DSL.name("ended_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>kuvasz.icmp_uptime_event.updated_at</code>.
     */
    public final TableField<IcmpUptimeEventRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    private IcmpUptimeEvent(Name alias, Table<IcmpUptimeEventRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private IcmpUptimeEvent(Name alias, Table<IcmpUptimeEventRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>kuvasz.icmp_uptime_event</code> table reference
     */
    public IcmpUptimeEvent(String alias) {
        this(DSL.name(alias), ICMP_UPTIME_EVENT);
    }

    /**
     * Create an aliased <code>kuvasz.icmp_uptime_event</code> table reference
     */
    public IcmpUptimeEvent(Name alias) {
        this(alias, ICMP_UPTIME_EVENT);
    }

    /**
     * Create a <code>kuvasz.icmp_uptime_event</code> table reference
     */
    public IcmpUptimeEvent() {
        this(DSL.name("icmp_uptime_event"), null);
    }

    public <O extends Record> IcmpUptimeEvent(Table<O> path, ForeignKey<O, IcmpUptimeEventRecord> childPath, InverseForeignKey<O, IcmpUptimeEventRecord> parentPath) {
        super(path, childPath, parentPath, ICMP_UPTIME_EVENT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class IcmpUptimeEventPath extends IcmpUptimeEvent implements Path<IcmpUptimeEventRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> IcmpUptimeEventPath(Table<O> path, ForeignKey<O, IcmpUptimeEventRecord> childPath, InverseForeignKey<O, IcmpUptimeEventRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private IcmpUptimeEventPath(Name alias, Table<IcmpUptimeEventRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public IcmpUptimeEventPath as(String alias) {
            return new IcmpUptimeEventPath(DSL.name(alias), this);
        }

        @Override
        public IcmpUptimeEventPath as(Name alias) {
            return new IcmpUptimeEventPath(alias, this);
        }

        @Override
        public IcmpUptimeEventPath as(Table<?> alias) {
            return new IcmpUptimeEventPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Kuvasz.KUVASZ;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ICMP_UPTIME_EVENT_ENDED_AT_IDX, Indexes.ICMP_UPTIME_EVENT_MONITOR_IDX);
    }

    @Override
    public UniqueKey<IcmpUptimeEventRecord> getPrimaryKey() {
        return Keys.ICMP_UPTIME_EVENT_PKEY;
    }

    @Override
    public List<UniqueKey<IcmpUptimeEventRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.ICMP_UPTIME_EVENT_KEY);
    }

    @Override
    public List<ForeignKey<IcmpUptimeEventRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ICMP_UPTIME_EVENT__ICMP_UPTIME_EVENT_MONITOR_ID_FKEY);
    }

    private transient IcmpMonitorPath _icmpMonitor;

    /**
     * Get the implicit join path to the <code>kuvasz.icmp_monitor</code> table.
     */
    public IcmpMonitorPath icmpMonitor() {
        if (_icmpMonitor == null)
            _icmpMonitor = new IcmpMonitorPath(this, Keys.ICMP_UPTIME_EVENT__ICMP_UPTIME_EVENT_MONITOR_ID_FKEY, null);

        return _icmpMonitor;
    }

    @Override
    public IcmpUptimeEvent as(String alias) {
        return new IcmpUptimeEvent(DSL.name(alias), this);
    }

    @Override
    public IcmpUptimeEvent as(Name alias) {
        return new IcmpUptimeEvent(alias, this);
    }

    @Override
    public IcmpUptimeEvent as(Table<?> alias) {
        return new IcmpUptimeEvent(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public IcmpUptimeEvent rename(String name) {
        return new IcmpUptimeEvent(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public IcmpUptimeEvent rename(Name name) {
        return new IcmpUptimeEvent(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public IcmpUptimeEvent rename(Table<?> name) {
        return new IcmpUptimeEvent(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IcmpUptimeEvent where(Condition condition) {
        return new IcmpUptimeEvent(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IcmpUptimeEvent where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IcmpUptimeEvent where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IcmpUptimeEvent where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IcmpUptimeEvent where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IcmpUptimeEvent where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IcmpUptimeEvent where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public IcmpUptimeEvent where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IcmpUptimeEvent whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public IcmpUptimeEvent whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
