/*
 * This file is generated by jOOQ.
 */
package com.kuvaszuptime.kuvasz.jooq.tables;


import com.kuvaszuptime.kuvasz.jooq.Indexes;
import com.kuvaszuptime.kuvasz.jooq.Keys;
import com.kuvaszuptime.kuvasz.jooq.Kuvasz;
import com.kuvaszuptime.kuvasz.jooq.TextArrayToIntegrationIdArrayConverter;
import com.kuvaszuptime.kuvasz.jooq.TextArrayToMonitorIdArrayConverter;
import com.kuvaszuptime.kuvasz.jooq.tables.records.MaintenanceWindowRecord;
import com.kuvaszuptime.kuvasz.models.handlers.IntegrationID;
import com.kuvaszuptime.kuvasz.models.monitor.MonitorID;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MaintenanceWindow extends TableImpl<MaintenanceWindowRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>kuvasz.maintenance_window</code>
     */
    public static final MaintenanceWindow MAINTENANCE_WINDOW = new MaintenanceWindow();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MaintenanceWindowRecord> getRecordType() {
        return MaintenanceWindowRecord.class;
    }

    /**
     * The column <code>kuvasz.maintenance_window.id</code>.
     */
    public final TableField<MaintenanceWindowRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>kuvasz.maintenance_window.name</code>.
     */
    public final TableField<MaintenanceWindowRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>kuvasz.maintenance_window.description</code>.
     */
    public final TableField<MaintenanceWindowRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>kuvasz.maintenance_window.enabled</code>.
     */
    public final TableField<MaintenanceWindowRecord, Boolean> ENABLED = createField(DSL.name("enabled"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>kuvasz.maintenance_window.global</code>.
     */
    public final TableField<MaintenanceWindowRecord, Boolean> GLOBAL = createField(DSL.name("global"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>kuvasz.maintenance_window.show_on_status_pages</code>.
     */
    public final TableField<MaintenanceWindowRecord, Boolean> SHOW_ON_STATUS_PAGES = createField(DSL.name("show_on_status_pages"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>kuvasz.maintenance_window.cron</code>.
     */
    public final TableField<MaintenanceWindowRecord, String> CRON = createField(DSL.name("cron"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>kuvasz.maintenance_window.start</code>.
     */
    public final TableField<MaintenanceWindowRecord, OffsetDateTime> START = createField(DSL.name("start"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>kuvasz.maintenance_window.duration</code>.
     */
    public final TableField<MaintenanceWindowRecord, String> DURATION = createField(DSL.name("duration"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>kuvasz.maintenance_window.monitors</code>.
     */
    public final TableField<MaintenanceWindowRecord, MonitorID[]> MONITORS = createField(DSL.name("monitors"), SQLDataType.CLOB.array().nullable(false).defaultValue(DSL.field(DSL.raw("ARRAY[]::text[]"), SQLDataType.CLOB.array())), this, "", new TextArrayToMonitorIdArrayConverter());

    /**
     * The column <code>kuvasz.maintenance_window.integrations</code>.
     */
    public final TableField<MaintenanceWindowRecord, IntegrationID[]> INTEGRATIONS = createField(DSL.name("integrations"), SQLDataType.CLOB.array().nullable(false).defaultValue(DSL.field(DSL.raw("ARRAY[]::text[]"), SQLDataType.CLOB.array())), this, "", new TextArrayToIntegrationIdArrayConverter());

    /**
     * The column <code>kuvasz.maintenance_window.created_at</code>.
     */
    public final TableField<MaintenanceWindowRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>kuvasz.maintenance_window.updated_at</code>.
     */
    public final TableField<MaintenanceWindowRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private MaintenanceWindow(Name alias, Table<MaintenanceWindowRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MaintenanceWindow(Name alias, Table<MaintenanceWindowRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>kuvasz.maintenance_window</code> table reference
     */
    public MaintenanceWindow(String alias) {
        this(DSL.name(alias), MAINTENANCE_WINDOW);
    }

    /**
     * Create an aliased <code>kuvasz.maintenance_window</code> table reference
     */
    public MaintenanceWindow(Name alias) {
        this(alias, MAINTENANCE_WINDOW);
    }

    /**
     * Create a <code>kuvasz.maintenance_window</code> table reference
     */
    public MaintenanceWindow() {
        this(DSL.name("maintenance_window"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Kuvasz.KUVASZ;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.MAINTENANCE_ENABLED_IDX, Indexes.MAINTENANCE_MONITORS_IDX);
    }

    @Override
    public UniqueKey<MaintenanceWindowRecord> getPrimaryKey() {
        return Keys.MAINTENANCE_WINDOW_PKEY;
    }

    @Override
    public List<UniqueKey<MaintenanceWindowRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.MAINTENANCE_WINDOW_NAME_KEY);
    }

    @Override
    public List<Check<MaintenanceWindowRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("cron_or_single_schedule"), "(((cron IS NULL) OR (start IS NULL)))", true),
            Internal.createCheck(this, DSL.name("cron_with_duration"), "(((cron IS NULL) OR ((cron IS NOT NULL) AND (duration IS NOT NULL))))", true),
            Internal.createCheck(this, DSL.name("single_with_duration"), "(((start IS NULL) OR ((start IS NOT NULL) AND (duration IS NOT NULL))))", true)
        );
    }

    @Override
    public MaintenanceWindow as(String alias) {
        return new MaintenanceWindow(DSL.name(alias), this);
    }

    @Override
    public MaintenanceWindow as(Name alias) {
        return new MaintenanceWindow(alias, this);
    }

    @Override
    public MaintenanceWindow as(Table<?> alias) {
        return new MaintenanceWindow(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MaintenanceWindow rename(String name) {
        return new MaintenanceWindow(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MaintenanceWindow rename(Name name) {
        return new MaintenanceWindow(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MaintenanceWindow rename(Table<?> name) {
        return new MaintenanceWindow(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MaintenanceWindow where(Condition condition) {
        return new MaintenanceWindow(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MaintenanceWindow where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MaintenanceWindow where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MaintenanceWindow where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MaintenanceWindow where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MaintenanceWindow where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MaintenanceWindow where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MaintenanceWindow where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MaintenanceWindow whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MaintenanceWindow whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
