/*
 * This file is generated by jOOQ.
 */
package com.kuvaszuptime.kuvasz.jooq.tables;


import com.kuvaszuptime.kuvasz.jooq.Keys;
import com.kuvaszuptime.kuvasz.jooq.Kuvasz;
import com.kuvaszuptime.kuvasz.jooq.tables.records.PendingFailureRecord;

import java.time.OffsetDateTime;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PendingFailure extends TableImpl<PendingFailureRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>kuvasz.pending_failure</code>
     */
    public static final PendingFailure PENDING_FAILURE = new PendingFailure();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PendingFailureRecord> getRecordType() {
        return PendingFailureRecord.class;
    }

    /**
     * The column <code>kuvasz.pending_failure.monitor_id</code>.
     */
    public final TableField<PendingFailureRecord, Long> MONITOR_ID = createField(DSL.name("monitor_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>kuvasz.pending_failure.failure_count</code>.
     */
    public final TableField<PendingFailureRecord, Long> FAILURE_COUNT = createField(DSL.name("failure_count"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>kuvasz.pending_failure.created_at</code>.
     */
    public final TableField<PendingFailureRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>kuvasz.pending_failure.updated_at</code>.
     */
    public final TableField<PendingFailureRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private PendingFailure(Name alias, Table<PendingFailureRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PendingFailure(Name alias, Table<PendingFailureRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>kuvasz.pending_failure</code> table reference
     */
    public PendingFailure(String alias) {
        this(DSL.name(alias), PENDING_FAILURE);
    }

    /**
     * Create an aliased <code>kuvasz.pending_failure</code> table reference
     */
    public PendingFailure(Name alias) {
        this(alias, PENDING_FAILURE);
    }

    /**
     * Create a <code>kuvasz.pending_failure</code> table reference
     */
    public PendingFailure() {
        this(DSL.name("pending_failure"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Kuvasz.KUVASZ;
    }

    @Override
    public UniqueKey<PendingFailureRecord> getPrimaryKey() {
        return Keys.PENDING_FAILURE_PKEY;
    }

    @Override
    public PendingFailure as(String alias) {
        return new PendingFailure(DSL.name(alias), this);
    }

    @Override
    public PendingFailure as(Name alias) {
        return new PendingFailure(alias, this);
    }

    @Override
    public PendingFailure as(Table<?> alias) {
        return new PendingFailure(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PendingFailure rename(String name) {
        return new PendingFailure(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PendingFailure rename(Name name) {
        return new PendingFailure(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PendingFailure rename(Table<?> name) {
        return new PendingFailure(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PendingFailure where(Condition condition) {
        return new PendingFailure(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PendingFailure where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PendingFailure where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PendingFailure where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PendingFailure where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PendingFailure where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PendingFailure where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PendingFailure where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PendingFailure whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PendingFailure whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
