/*
 * This file is generated by jOOQ.
 */
package com.kuvaszuptime.kuvasz.jooq.tables;


import com.kuvaszuptime.kuvasz.jooq.Indexes;
import com.kuvaszuptime.kuvasz.jooq.Keys;
import com.kuvaszuptime.kuvasz.jooq.Kuvasz;
import com.kuvaszuptime.kuvasz.jooq.TextArrayToIntegrationIdArrayConverter;
import com.kuvaszuptime.kuvasz.jooq.tables.PushUptimeEvent.PushUptimeEventPath;
import com.kuvaszuptime.kuvasz.jooq.tables.records.PushMonitorRecord;
import com.kuvaszuptime.kuvasz.models.handlers.IntegrationID;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PushMonitor extends TableImpl<PushMonitorRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>kuvasz.push_monitor</code>
     */
    public static final PushMonitor PUSH_MONITOR = new PushMonitor();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PushMonitorRecord> getRecordType() {
        return PushMonitorRecord.class;
    }

    /**
     * The column <code>kuvasz.push_monitor.id</code>.
     */
    public final TableField<PushMonitorRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>kuvasz.push_monitor.name</code>.
     */
    public final TableField<PushMonitorRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>kuvasz.push_monitor.heartbeat_interval</code>.
     */
    public final TableField<PushMonitorRecord, Long> HEARTBEAT_INTERVAL = createField(DSL.name("heartbeat_interval"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>kuvasz.push_monitor.grace_period</code>.
     */
    public final TableField<PushMonitorRecord, Long> GRACE_PERIOD = createField(DSL.name("grace_period"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>kuvasz.push_monitor.last_heartbeat</code>.
     */
    public final TableField<PushMonitorRecord, OffsetDateTime> LAST_HEARTBEAT = createField(DSL.name("last_heartbeat"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>kuvasz.push_monitor.enabled</code>.
     */
    public final TableField<PushMonitorRecord, Boolean> ENABLED = createField(DSL.name("enabled"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>kuvasz.push_monitor.client_secret</code>.
     */
    public final TableField<PushMonitorRecord, String> CLIENT_SECRET = createField(DSL.name("client_secret"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>kuvasz.push_monitor.integrations</code>.
     */
    public final TableField<PushMonitorRecord, IntegrationID[]> INTEGRATIONS = createField(DSL.name("integrations"), SQLDataType.CLOB.array().nullable(false).defaultValue(DSL.field(DSL.raw("ARRAY[]::text[]"), SQLDataType.CLOB.array())), this, "", new TextArrayToIntegrationIdArrayConverter());

    /**
     * The column <code>kuvasz.push_monitor.created_at</code>.
     */
    public final TableField<PushMonitorRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>kuvasz.push_monitor.updated_at</code>.
     */
    public final TableField<PushMonitorRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>kuvasz.push_monitor.failure_count_threshold</code>.
     */
    public final TableField<PushMonitorRecord, Long> FAILURE_COUNT_THRESHOLD = createField(DSL.name("failure_count_threshold"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.BIGINT)), this, "");

    private PushMonitor(Name alias, Table<PushMonitorRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PushMonitor(Name alias, Table<PushMonitorRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>kuvasz.push_monitor</code> table reference
     */
    public PushMonitor(String alias) {
        this(DSL.name(alias), PUSH_MONITOR);
    }

    /**
     * Create an aliased <code>kuvasz.push_monitor</code> table reference
     */
    public PushMonitor(Name alias) {
        this(alias, PUSH_MONITOR);
    }

    /**
     * Create a <code>kuvasz.push_monitor</code> table reference
     */
    public PushMonitor() {
        this(DSL.name("push_monitor"), null);
    }

    public <O extends Record> PushMonitor(Table<O> path, ForeignKey<O, PushMonitorRecord> childPath, InverseForeignKey<O, PushMonitorRecord> parentPath) {
        super(path, childPath, parentPath, PUSH_MONITOR);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PushMonitorPath extends PushMonitor implements Path<PushMonitorRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PushMonitorPath(Table<O> path, ForeignKey<O, PushMonitorRecord> childPath, InverseForeignKey<O, PushMonitorRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PushMonitorPath(Name alias, Table<PushMonitorRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PushMonitorPath as(String alias) {
            return new PushMonitorPath(DSL.name(alias), this);
        }

        @Override
        public PushMonitorPath as(Name alias) {
            return new PushMonitorPath(alias, this);
        }

        @Override
        public PushMonitorPath as(Table<?> alias) {
            return new PushMonitorPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Kuvasz.KUVASZ;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.PUSH_MONITOR_EFFECTIVE_MONITORS_IDX);
    }

    @Override
    public UniqueKey<PushMonitorRecord> getPrimaryKey() {
        return Keys.PUSH_MONITOR_PKEY;
    }

    @Override
    public List<UniqueKey<PushMonitorRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UNIQUE_PUSH_CLIENT_SECRET, Keys.UNIQUE_PUSH_MONITOR_NAME);
    }

    private transient PushUptimeEventPath _pushUptimeEvent;

    /**
     * Get the implicit to-many join path to the
     * <code>kuvasz.push_uptime_event</code> table
     */
    public PushUptimeEventPath pushUptimeEvent() {
        if (_pushUptimeEvent == null)
            _pushUptimeEvent = new PushUptimeEventPath(this, null, Keys.PUSH_UPTIME_EVENT__PUSH_UPTIME_EVENT_MONITOR_ID_FKEY.getInverseKey());

        return _pushUptimeEvent;
    }

    @Override
    public PushMonitor as(String alias) {
        return new PushMonitor(DSL.name(alias), this);
    }

    @Override
    public PushMonitor as(Name alias) {
        return new PushMonitor(alias, this);
    }

    @Override
    public PushMonitor as(Table<?> alias) {
        return new PushMonitor(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PushMonitor rename(String name) {
        return new PushMonitor(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PushMonitor rename(Name name) {
        return new PushMonitor(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PushMonitor rename(Table<?> name) {
        return new PushMonitor(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PushMonitor where(Condition condition) {
        return new PushMonitor(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PushMonitor where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PushMonitor where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PushMonitor where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PushMonitor where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PushMonitor where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PushMonitor where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PushMonitor where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PushMonitor whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PushMonitor whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
