/*
 * This file is generated by jOOQ.
 */
package com.kuvaszuptime.kuvasz.jooq.tables;


import com.kuvaszuptime.kuvasz.jooq.Indexes;
import com.kuvaszuptime.kuvasz.jooq.Keys;
import com.kuvaszuptime.kuvasz.jooq.Kuvasz;
import com.kuvaszuptime.kuvasz.jooq.enums.UptimeStatus;
import com.kuvaszuptime.kuvasz.jooq.tables.PushMonitor.PushMonitorPath;
import com.kuvaszuptime.kuvasz.jooq.tables.records.PushUptimeEventRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PushUptimeEvent extends TableImpl<PushUptimeEventRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>kuvasz.push_uptime_event</code>
     */
    public static final PushUptimeEvent PUSH_UPTIME_EVENT = new PushUptimeEvent();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PushUptimeEventRecord> getRecordType() {
        return PushUptimeEventRecord.class;
    }

    /**
     * The column <code>kuvasz.push_uptime_event.id</code>.
     */
    public final TableField<PushUptimeEventRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>kuvasz.push_uptime_event.monitor_id</code>.
     */
    public final TableField<PushUptimeEventRecord, Long> MONITOR_ID = createField(DSL.name("monitor_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>kuvasz.push_uptime_event.status</code>.
     */
    public final TableField<PushUptimeEventRecord, UptimeStatus> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(UptimeStatus.class), this, "");

    /**
     * The column <code>kuvasz.push_uptime_event.error</code>.
     */
    public final TableField<PushUptimeEventRecord, String> ERROR = createField(DSL.name("error"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>kuvasz.push_uptime_event.started_at</code>.
     */
    public final TableField<PushUptimeEventRecord, OffsetDateTime> STARTED_AT = createField(DSL.name("started_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>kuvasz.push_uptime_event.ended_at</code>.
     */
    public final TableField<PushUptimeEventRecord, OffsetDateTime> ENDED_AT = createField(DSL.name("ended_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>kuvasz.push_uptime_event.updated_at</code>.
     */
    public final TableField<PushUptimeEventRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>kuvasz.push_uptime_event.failure_count</code>.
     */
    public final TableField<PushUptimeEventRecord, Long> FAILURE_COUNT = createField(DSL.name("failure_count"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    private PushUptimeEvent(Name alias, Table<PushUptimeEventRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PushUptimeEvent(Name alias, Table<PushUptimeEventRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>kuvasz.push_uptime_event</code> table reference
     */
    public PushUptimeEvent(String alias) {
        this(DSL.name(alias), PUSH_UPTIME_EVENT);
    }

    /**
     * Create an aliased <code>kuvasz.push_uptime_event</code> table reference
     */
    public PushUptimeEvent(Name alias) {
        this(alias, PUSH_UPTIME_EVENT);
    }

    /**
     * Create a <code>kuvasz.push_uptime_event</code> table reference
     */
    public PushUptimeEvent() {
        this(DSL.name("push_uptime_event"), null);
    }

    public <O extends Record> PushUptimeEvent(Table<O> path, ForeignKey<O, PushUptimeEventRecord> childPath, InverseForeignKey<O, PushUptimeEventRecord> parentPath) {
        super(path, childPath, parentPath, PUSH_UPTIME_EVENT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class PushUptimeEventPath extends PushUptimeEvent implements Path<PushUptimeEventRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> PushUptimeEventPath(Table<O> path, ForeignKey<O, PushUptimeEventRecord> childPath, InverseForeignKey<O, PushUptimeEventRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private PushUptimeEventPath(Name alias, Table<PushUptimeEventRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public PushUptimeEventPath as(String alias) {
            return new PushUptimeEventPath(DSL.name(alias), this);
        }

        @Override
        public PushUptimeEventPath as(Name alias) {
            return new PushUptimeEventPath(alias, this);
        }

        @Override
        public PushUptimeEventPath as(Table<?> alias) {
            return new PushUptimeEventPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Kuvasz.KUVASZ;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.PUSH_UPTIME_EVENT_ENDED_AT_IDX, Indexes.PUSH_UPTIME_EVENT_MONITOR_IDX);
    }

    @Override
    public Identity<PushUptimeEventRecord, Long> getIdentity() {
        return (Identity<PushUptimeEventRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<PushUptimeEventRecord> getPrimaryKey() {
        return Keys.PUSH_UPTIME_EVENT_PKEY;
    }

    @Override
    public List<UniqueKey<PushUptimeEventRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.PUSH_UPTIME_EVENT_KEY);
    }

    @Override
    public List<ForeignKey<PushUptimeEventRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PUSH_UPTIME_EVENT__PUSH_UPTIME_EVENT_MONITOR_ID_FKEY);
    }

    private transient PushMonitorPath _pushMonitor;

    /**
     * Get the implicit join path to the <code>kuvasz.push_monitor</code> table.
     */
    public PushMonitorPath pushMonitor() {
        if (_pushMonitor == null)
            _pushMonitor = new PushMonitorPath(this, Keys.PUSH_UPTIME_EVENT__PUSH_UPTIME_EVENT_MONITOR_ID_FKEY, null);

        return _pushMonitor;
    }

    @Override
    public PushUptimeEvent as(String alias) {
        return new PushUptimeEvent(DSL.name(alias), this);
    }

    @Override
    public PushUptimeEvent as(Name alias) {
        return new PushUptimeEvent(alias, this);
    }

    @Override
    public PushUptimeEvent as(Table<?> alias) {
        return new PushUptimeEvent(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PushUptimeEvent rename(String name) {
        return new PushUptimeEvent(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PushUptimeEvent rename(Name name) {
        return new PushUptimeEvent(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PushUptimeEvent rename(Table<?> name) {
        return new PushUptimeEvent(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PushUptimeEvent where(Condition condition) {
        return new PushUptimeEvent(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PushUptimeEvent where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PushUptimeEvent where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PushUptimeEvent where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PushUptimeEvent where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PushUptimeEvent where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PushUptimeEvent where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PushUptimeEvent where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PushUptimeEvent whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PushUptimeEvent whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
