/*
 * This file is generated by jOOQ.
 */
package com.kuvaszuptime.kuvasz.jooq.tables;


import com.kuvaszuptime.kuvasz.jooq.Indexes;
import com.kuvaszuptime.kuvasz.jooq.Keys;
import com.kuvaszuptime.kuvasz.jooq.Kuvasz;
import com.kuvaszuptime.kuvasz.jooq.TextArrayToIntegrationIdArrayConverter;
import com.kuvaszuptime.kuvasz.jooq.tables.TcpMetricsLog.TcpMetricsLogPath;
import com.kuvaszuptime.kuvasz.jooq.tables.TcpUptimeEvent.TcpUptimeEventPath;
import com.kuvaszuptime.kuvasz.jooq.tables.records.TcpMonitorRecord;
import com.kuvaszuptime.kuvasz.models.handlers.IntegrationID;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TcpMonitor extends TableImpl<TcpMonitorRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>kuvasz.tcp_monitor</code>
     */
    public static final TcpMonitor TCP_MONITOR = new TcpMonitor();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TcpMonitorRecord> getRecordType() {
        return TcpMonitorRecord.class;
    }

    /**
     * The column <code>kuvasz.tcp_monitor.id</code>.
     */
    public final TableField<TcpMonitorRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>kuvasz.tcp_monitor.name</code>.
     */
    public final TableField<TcpMonitorRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>kuvasz.tcp_monitor.host</code>.
     */
    public final TableField<TcpMonitorRecord, String> HOST = createField(DSL.name("host"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>kuvasz.tcp_monitor.port</code>.
     */
    public final TableField<TcpMonitorRecord, Integer> PORT = createField(DSL.name("port"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>kuvasz.tcp_monitor.uptime_check_interval</code>.
     */
    public final TableField<TcpMonitorRecord, Integer> UPTIME_CHECK_INTERVAL = createField(DSL.name("uptime_check_interval"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>kuvasz.tcp_monitor.timeout_ms</code>.
     */
    public final TableField<TcpMonitorRecord, Integer> TIMEOUT_MS = createField(DSL.name("timeout_ms"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("5000"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>kuvasz.tcp_monitor.latency_threshold_ms</code>.
     */
    public final TableField<TcpMonitorRecord, Integer> LATENCY_THRESHOLD_MS = createField(DSL.name("latency_threshold_ms"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>kuvasz.tcp_monitor.failure_count_threshold</code>.
     */
    public final TableField<TcpMonitorRecord, Long> FAILURE_COUNT_THRESHOLD = createField(DSL.name("failure_count_threshold"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>kuvasz.tcp_monitor.enabled</code>.
     */
    public final TableField<TcpMonitorRecord, Boolean> ENABLED = createField(DSL.name("enabled"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>kuvasz.tcp_monitor.metrics_history_enabled</code>.
     */
    public final TableField<TcpMonitorRecord, Boolean> METRICS_HISTORY_ENABLED = createField(DSL.name("metrics_history_enabled"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>kuvasz.tcp_monitor.integrations</code>.
     */
    public final TableField<TcpMonitorRecord, IntegrationID[]> INTEGRATIONS = createField(DSL.name("integrations"), SQLDataType.CLOB.array().nullable(false).defaultValue(DSL.field(DSL.raw("ARRAY[]::text[]"), SQLDataType.CLOB.array())), this, "", new TextArrayToIntegrationIdArrayConverter());

    /**
     * The column <code>kuvasz.tcp_monitor.created_at</code>.
     */
    public final TableField<TcpMonitorRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>kuvasz.tcp_monitor.updated_at</code>.
     */
    public final TableField<TcpMonitorRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private TcpMonitor(Name alias, Table<TcpMonitorRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TcpMonitor(Name alias, Table<TcpMonitorRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>kuvasz.tcp_monitor</code> table reference
     */
    public TcpMonitor(String alias) {
        this(DSL.name(alias), TCP_MONITOR);
    }

    /**
     * Create an aliased <code>kuvasz.tcp_monitor</code> table reference
     */
    public TcpMonitor(Name alias) {
        this(alias, TCP_MONITOR);
    }

    /**
     * Create a <code>kuvasz.tcp_monitor</code> table reference
     */
    public TcpMonitor() {
        this(DSL.name("tcp_monitor"), null);
    }

    public <O extends Record> TcpMonitor(Table<O> path, ForeignKey<O, TcpMonitorRecord> childPath, InverseForeignKey<O, TcpMonitorRecord> parentPath) {
        super(path, childPath, parentPath, TCP_MONITOR);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TcpMonitorPath extends TcpMonitor implements Path<TcpMonitorRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TcpMonitorPath(Table<O> path, ForeignKey<O, TcpMonitorRecord> childPath, InverseForeignKey<O, TcpMonitorRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TcpMonitorPath(Name alias, Table<TcpMonitorRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TcpMonitorPath as(String alias) {
            return new TcpMonitorPath(DSL.name(alias), this);
        }

        @Override
        public TcpMonitorPath as(Name alias) {
            return new TcpMonitorPath(alias, this);
        }

        @Override
        public TcpMonitorPath as(Table<?> alias) {
            return new TcpMonitorPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Kuvasz.KUVASZ;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.TCP_MONITOR_ENABLED_IDX);
    }

    @Override
    public UniqueKey<TcpMonitorRecord> getPrimaryKey() {
        return Keys.TCP_MONITOR_PKEY;
    }

    @Override
    public List<UniqueKey<TcpMonitorRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UNIQUE_TCP_MONITOR_NAME);
    }

    private transient TcpMetricsLogPath _tcpMetricsLog;

    /**
     * Get the implicit to-many join path to the
     * <code>kuvasz.tcp_metrics_log</code> table
     */
    public TcpMetricsLogPath tcpMetricsLog() {
        if (_tcpMetricsLog == null)
            _tcpMetricsLog = new TcpMetricsLogPath(this, null, Keys.TCP_METRICS_LOG__TCP_METRICS_LOG_MONITOR_ID_FKEY.getInverseKey());

        return _tcpMetricsLog;
    }

    private transient TcpUptimeEventPath _tcpUptimeEvent;

    /**
     * Get the implicit to-many join path to the
     * <code>kuvasz.tcp_uptime_event</code> table
     */
    public TcpUptimeEventPath tcpUptimeEvent() {
        if (_tcpUptimeEvent == null)
            _tcpUptimeEvent = new TcpUptimeEventPath(this, null, Keys.TCP_UPTIME_EVENT__TCP_UPTIME_EVENT_MONITOR_ID_FKEY.getInverseKey());

        return _tcpUptimeEvent;
    }

    @Override
    public TcpMonitor as(String alias) {
        return new TcpMonitor(DSL.name(alias), this);
    }

    @Override
    public TcpMonitor as(Name alias) {
        return new TcpMonitor(alias, this);
    }

    @Override
    public TcpMonitor as(Table<?> alias) {
        return new TcpMonitor(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TcpMonitor rename(String name) {
        return new TcpMonitor(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TcpMonitor rename(Name name) {
        return new TcpMonitor(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TcpMonitor rename(Table<?> name) {
        return new TcpMonitor(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TcpMonitor where(Condition condition) {
        return new TcpMonitor(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TcpMonitor where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TcpMonitor where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TcpMonitor where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TcpMonitor where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TcpMonitor where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TcpMonitor where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TcpMonitor where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TcpMonitor whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TcpMonitor whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
