/*
 * This file is generated by jOOQ.
 */
package com.kuvaszuptime.kuvasz.jooq.tables.pojos;


import com.kuvaszuptime.kuvasz.models.handlers.IntegrationID;

import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.Arrays;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DockerMonitor implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String name;
    private String dockerHost;
    private String container;
    private Integer uptimeCheckInterval;
    private Integer timeoutMs;
    private Long failureCountThreshold;
    private Boolean enabled;
    private Boolean metricsHistoryEnabled;
    private IntegrationID[] integrations;
    private String category;
    private Boolean ignoreConnectivityCheck;
    private OffsetDateTime createdAt;
    private OffsetDateTime updatedAt;

    public DockerMonitor() {}

    public DockerMonitor(DockerMonitor value) {
        this.id = value.id;
        this.name = value.name;
        this.dockerHost = value.dockerHost;
        this.container = value.container;
        this.uptimeCheckInterval = value.uptimeCheckInterval;
        this.timeoutMs = value.timeoutMs;
        this.failureCountThreshold = value.failureCountThreshold;
        this.enabled = value.enabled;
        this.metricsHistoryEnabled = value.metricsHistoryEnabled;
        this.integrations = value.integrations;
        this.category = value.category;
        this.ignoreConnectivityCheck = value.ignoreConnectivityCheck;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public DockerMonitor(
        Long id,
        String name,
        String dockerHost,
        String container,
        Integer uptimeCheckInterval,
        Integer timeoutMs,
        Long failureCountThreshold,
        Boolean enabled,
        Boolean metricsHistoryEnabled,
        IntegrationID[] integrations,
        String category,
        Boolean ignoreConnectivityCheck,
        OffsetDateTime createdAt,
        OffsetDateTime updatedAt
    ) {
        this.id = id;
        this.name = name;
        this.dockerHost = dockerHost;
        this.container = container;
        this.uptimeCheckInterval = uptimeCheckInterval;
        this.timeoutMs = timeoutMs;
        this.failureCountThreshold = failureCountThreshold;
        this.enabled = enabled;
        this.metricsHistoryEnabled = metricsHistoryEnabled;
        this.integrations = integrations;
        this.category = category;
        this.ignoreConnectivityCheck = ignoreConnectivityCheck;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>kuvasz.docker_monitor.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>kuvasz.docker_monitor.id</code>.
     */
    public DockerMonitor setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>kuvasz.docker_monitor.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>kuvasz.docker_monitor.name</code>.
     */
    public DockerMonitor setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>kuvasz.docker_monitor.docker_host</code>.
     */
    public String getDockerHost() {
        return this.dockerHost;
    }

    /**
     * Setter for <code>kuvasz.docker_monitor.docker_host</code>.
     */
    public DockerMonitor setDockerHost(String dockerHost) {
        this.dockerHost = dockerHost;
        return this;
    }

    /**
     * Getter for <code>kuvasz.docker_monitor.container</code>.
     */
    public String getContainer() {
        return this.container;
    }

    /**
     * Setter for <code>kuvasz.docker_monitor.container</code>.
     */
    public DockerMonitor setContainer(String container) {
        this.container = container;
        return this;
    }

    /**
     * Getter for <code>kuvasz.docker_monitor.uptime_check_interval</code>.
     */
    public Integer getUptimeCheckInterval() {
        return this.uptimeCheckInterval;
    }

    /**
     * Setter for <code>kuvasz.docker_monitor.uptime_check_interval</code>.
     */
    public DockerMonitor setUptimeCheckInterval(Integer uptimeCheckInterval) {
        this.uptimeCheckInterval = uptimeCheckInterval;
        return this;
    }

    /**
     * Getter for <code>kuvasz.docker_monitor.timeout_ms</code>.
     */
    public Integer getTimeoutMs() {
        return this.timeoutMs;
    }

    /**
     * Setter for <code>kuvasz.docker_monitor.timeout_ms</code>.
     */
    public DockerMonitor setTimeoutMs(Integer timeoutMs) {
        this.timeoutMs = timeoutMs;
        return this;
    }

    /**
     * Getter for <code>kuvasz.docker_monitor.failure_count_threshold</code>.
     */
    public Long getFailureCountThreshold() {
        return this.failureCountThreshold;
    }

    /**
     * Setter for <code>kuvasz.docker_monitor.failure_count_threshold</code>.
     */
    public DockerMonitor setFailureCountThreshold(Long failureCountThreshold) {
        this.failureCountThreshold = failureCountThreshold;
        return this;
    }

    /**
     * Getter for <code>kuvasz.docker_monitor.enabled</code>.
     */
    public Boolean getEnabled() {
        return this.enabled;
    }

    /**
     * Setter for <code>kuvasz.docker_monitor.enabled</code>.
     */
    public DockerMonitor setEnabled(Boolean enabled) {
        this.enabled = enabled;
        return this;
    }

    /**
     * Getter for <code>kuvasz.docker_monitor.metrics_history_enabled</code>.
     */
    public Boolean getMetricsHistoryEnabled() {
        return this.metricsHistoryEnabled;
    }

    /**
     * Setter for <code>kuvasz.docker_monitor.metrics_history_enabled</code>.
     */
    public DockerMonitor setMetricsHistoryEnabled(Boolean metricsHistoryEnabled) {
        this.metricsHistoryEnabled = metricsHistoryEnabled;
        return this;
    }

    /**
     * Getter for <code>kuvasz.docker_monitor.integrations</code>.
     */
    public IntegrationID[] getIntegrations() {
        return this.integrations;
    }

    /**
     * Setter for <code>kuvasz.docker_monitor.integrations</code>.
     */
    public DockerMonitor setIntegrations(IntegrationID[] integrations) {
        this.integrations = integrations;
        return this;
    }

    /**
     * Getter for <code>kuvasz.docker_monitor.category</code>.
     */
    public String getCategory() {
        return this.category;
    }

    /**
     * Setter for <code>kuvasz.docker_monitor.category</code>.
     */
    public DockerMonitor setCategory(String category) {
        this.category = category;
        return this;
    }

    /**
     * Getter for <code>kuvasz.docker_monitor.ignore_connectivity_check</code>.
     */
    public Boolean getIgnoreConnectivityCheck() {
        return this.ignoreConnectivityCheck;
    }

    /**
     * Setter for <code>kuvasz.docker_monitor.ignore_connectivity_check</code>.
     */
    public DockerMonitor setIgnoreConnectivityCheck(Boolean ignoreConnectivityCheck) {
        this.ignoreConnectivityCheck = ignoreConnectivityCheck;
        return this;
    }

    /**
     * Getter for <code>kuvasz.docker_monitor.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>kuvasz.docker_monitor.created_at</code>.
     */
    public DockerMonitor setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Getter for <code>kuvasz.docker_monitor.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>kuvasz.docker_monitor.updated_at</code>.
     */
    public DockerMonitor setUpdatedAt(OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final DockerMonitor other = (DockerMonitor) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.dockerHost == null) {
            if (other.dockerHost != null)
                return false;
        }
        else if (!this.dockerHost.equals(other.dockerHost))
            return false;
        if (this.container == null) {
            if (other.container != null)
                return false;
        }
        else if (!this.container.equals(other.container))
            return false;
        if (this.uptimeCheckInterval == null) {
            if (other.uptimeCheckInterval != null)
                return false;
        }
        else if (!this.uptimeCheckInterval.equals(other.uptimeCheckInterval))
            return false;
        if (this.timeoutMs == null) {
            if (other.timeoutMs != null)
                return false;
        }
        else if (!this.timeoutMs.equals(other.timeoutMs))
            return false;
        if (this.failureCountThreshold == null) {
            if (other.failureCountThreshold != null)
                return false;
        }
        else if (!this.failureCountThreshold.equals(other.failureCountThreshold))
            return false;
        if (this.enabled == null) {
            if (other.enabled != null)
                return false;
        }
        else if (!this.enabled.equals(other.enabled))
            return false;
        if (this.metricsHistoryEnabled == null) {
            if (other.metricsHistoryEnabled != null)
                return false;
        }
        else if (!this.metricsHistoryEnabled.equals(other.metricsHistoryEnabled))
            return false;
        if (this.integrations == null) {
            if (other.integrations != null)
                return false;
        }
        else if (!Arrays.deepEquals(this.integrations, other.integrations))
            return false;
        if (this.category == null) {
            if (other.category != null)
                return false;
        }
        else if (!this.category.equals(other.category))
            return false;
        if (this.ignoreConnectivityCheck == null) {
            if (other.ignoreConnectivityCheck != null)
                return false;
        }
        else if (!this.ignoreConnectivityCheck.equals(other.ignoreConnectivityCheck))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.dockerHost == null) ? 0 : this.dockerHost.hashCode());
        result = prime * result + ((this.container == null) ? 0 : this.container.hashCode());
        result = prime * result + ((this.uptimeCheckInterval == null) ? 0 : this.uptimeCheckInterval.hashCode());
        result = prime * result + ((this.timeoutMs == null) ? 0 : this.timeoutMs.hashCode());
        result = prime * result + ((this.failureCountThreshold == null) ? 0 : this.failureCountThreshold.hashCode());
        result = prime * result + ((this.enabled == null) ? 0 : this.enabled.hashCode());
        result = prime * result + ((this.metricsHistoryEnabled == null) ? 0 : this.metricsHistoryEnabled.hashCode());
        result = prime * result + ((this.integrations == null) ? 0 : Arrays.deepHashCode(this.integrations));
        result = prime * result + ((this.category == null) ? 0 : this.category.hashCode());
        result = prime * result + ((this.ignoreConnectivityCheck == null) ? 0 : this.ignoreConnectivityCheck.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DockerMonitor (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(dockerHost);
        sb.append(", ").append(container);
        sb.append(", ").append(uptimeCheckInterval);
        sb.append(", ").append(timeoutMs);
        sb.append(", ").append(failureCountThreshold);
        sb.append(", ").append(enabled);
        sb.append(", ").append(metricsHistoryEnabled);
        sb.append(", ").append(Arrays.deepToString(integrations));
        sb.append(", ").append(category);
        sb.append(", ").append(ignoreConnectivityCheck);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
