/*
 * This file is generated by jOOQ.
 */
package com.kuvaszuptime.kuvasz.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class IcmpMetricsLog implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long monitorId;
    private Integer latencyMs;
    private Integer packetLossPercentage;
    private OffsetDateTime createdAt;

    public IcmpMetricsLog() {}

    public IcmpMetricsLog(IcmpMetricsLog value) {
        this.id = value.id;
        this.monitorId = value.monitorId;
        this.latencyMs = value.latencyMs;
        this.packetLossPercentage = value.packetLossPercentage;
        this.createdAt = value.createdAt;
    }

    public IcmpMetricsLog(
        Long id,
        Long monitorId,
        Integer latencyMs,
        Integer packetLossPercentage,
        OffsetDateTime createdAt
    ) {
        this.id = id;
        this.monitorId = monitorId;
        this.latencyMs = latencyMs;
        this.packetLossPercentage = packetLossPercentage;
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>kuvasz.icmp_metrics_log.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>kuvasz.icmp_metrics_log.id</code>.
     */
    public IcmpMetricsLog setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>kuvasz.icmp_metrics_log.monitor_id</code>.
     */
    public Long getMonitorId() {
        return this.monitorId;
    }

    /**
     * Setter for <code>kuvasz.icmp_metrics_log.monitor_id</code>.
     */
    public IcmpMetricsLog setMonitorId(Long monitorId) {
        this.monitorId = monitorId;
        return this;
    }

    /**
     * Getter for <code>kuvasz.icmp_metrics_log.latency_ms</code>.
     */
    public Integer getLatencyMs() {
        return this.latencyMs;
    }

    /**
     * Setter for <code>kuvasz.icmp_metrics_log.latency_ms</code>.
     */
    public IcmpMetricsLog setLatencyMs(Integer latencyMs) {
        this.latencyMs = latencyMs;
        return this;
    }

    /**
     * Getter for <code>kuvasz.icmp_metrics_log.packet_loss_percentage</code>.
     */
    public Integer getPacketLossPercentage() {
        return this.packetLossPercentage;
    }

    /**
     * Setter for <code>kuvasz.icmp_metrics_log.packet_loss_percentage</code>.
     */
    public IcmpMetricsLog setPacketLossPercentage(Integer packetLossPercentage) {
        this.packetLossPercentage = packetLossPercentage;
        return this;
    }

    /**
     * Getter for <code>kuvasz.icmp_metrics_log.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>kuvasz.icmp_metrics_log.created_at</code>.
     */
    public IcmpMetricsLog setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final IcmpMetricsLog other = (IcmpMetricsLog) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.monitorId == null) {
            if (other.monitorId != null)
                return false;
        }
        else if (!this.monitorId.equals(other.monitorId))
            return false;
        if (this.latencyMs == null) {
            if (other.latencyMs != null)
                return false;
        }
        else if (!this.latencyMs.equals(other.latencyMs))
            return false;
        if (this.packetLossPercentage == null) {
            if (other.packetLossPercentage != null)
                return false;
        }
        else if (!this.packetLossPercentage.equals(other.packetLossPercentage))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.monitorId == null) ? 0 : this.monitorId.hashCode());
        result = prime * result + ((this.latencyMs == null) ? 0 : this.latencyMs.hashCode());
        result = prime * result + ((this.packetLossPercentage == null) ? 0 : this.packetLossPercentage.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("IcmpMetricsLog (");

        sb.append(id);
        sb.append(", ").append(monitorId);
        sb.append(", ").append(latencyMs);
        sb.append(", ").append(packetLossPercentage);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
