/*
 * This file is generated by jOOQ.
 */
package com.kuvaszuptime.kuvasz.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PendingFailure implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long monitorId;
    private Long failureCount;
    private OffsetDateTime createdAt;
    private OffsetDateTime updatedAt;

    public PendingFailure() {}

    public PendingFailure(PendingFailure value) {
        this.monitorId = value.monitorId;
        this.failureCount = value.failureCount;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public PendingFailure(
        Long monitorId,
        Long failureCount,
        OffsetDateTime createdAt,
        OffsetDateTime updatedAt
    ) {
        this.monitorId = monitorId;
        this.failureCount = failureCount;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>kuvasz.pending_failure.monitor_id</code>.
     */
    public Long getMonitorId() {
        return this.monitorId;
    }

    /**
     * Setter for <code>kuvasz.pending_failure.monitor_id</code>.
     */
    public PendingFailure setMonitorId(Long monitorId) {
        this.monitorId = monitorId;
        return this;
    }

    /**
     * Getter for <code>kuvasz.pending_failure.failure_count</code>.
     */
    public Long getFailureCount() {
        return this.failureCount;
    }

    /**
     * Setter for <code>kuvasz.pending_failure.failure_count</code>.
     */
    public PendingFailure setFailureCount(Long failureCount) {
        this.failureCount = failureCount;
        return this;
    }

    /**
     * Getter for <code>kuvasz.pending_failure.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>kuvasz.pending_failure.created_at</code>.
     */
    public PendingFailure setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Getter for <code>kuvasz.pending_failure.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>kuvasz.pending_failure.updated_at</code>.
     */
    public PendingFailure setUpdatedAt(OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PendingFailure other = (PendingFailure) obj;
        if (this.monitorId == null) {
            if (other.monitorId != null)
                return false;
        }
        else if (!this.monitorId.equals(other.monitorId))
            return false;
        if (this.failureCount == null) {
            if (other.failureCount != null)
                return false;
        }
        else if (!this.failureCount.equals(other.failureCount))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.monitorId == null) ? 0 : this.monitorId.hashCode());
        result = prime * result + ((this.failureCount == null) ? 0 : this.failureCount.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PendingFailure (");

        sb.append(monitorId);
        sb.append(", ").append(failureCount);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
