/*
 * This file is generated by jOOQ.
 */
package com.kuvaszuptime.kuvasz.jooq.tables.pojos;


import com.kuvaszuptime.kuvasz.models.MonitorID;

import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.Arrays;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class StatusPage implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String title;
    private String slug;
    private Boolean enabled;
    private MonitorID[] monitors;
    private OffsetDateTime createdAt;
    private OffsetDateTime updatedAt;

    public StatusPage() {}

    public StatusPage(StatusPage value) {
        this.id = value.id;
        this.title = value.title;
        this.slug = value.slug;
        this.enabled = value.enabled;
        this.monitors = value.monitors;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public StatusPage(
        Long id,
        String title,
        String slug,
        Boolean enabled,
        MonitorID[] monitors,
        OffsetDateTime createdAt,
        OffsetDateTime updatedAt
    ) {
        this.id = id;
        this.title = title;
        this.slug = slug;
        this.enabled = enabled;
        this.monitors = monitors;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>kuvasz.status_page.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>kuvasz.status_page.id</code>.
     */
    public StatusPage setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>kuvasz.status_page.title</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>kuvasz.status_page.title</code>.
     */
    public StatusPage setTitle(String title) {
        this.title = title;
        return this;
    }

    /**
     * Getter for <code>kuvasz.status_page.slug</code>.
     */
    public String getSlug() {
        return this.slug;
    }

    /**
     * Setter for <code>kuvasz.status_page.slug</code>.
     */
    public StatusPage setSlug(String slug) {
        this.slug = slug;
        return this;
    }

    /**
     * Getter for <code>kuvasz.status_page.enabled</code>.
     */
    public Boolean getEnabled() {
        return this.enabled;
    }

    /**
     * Setter for <code>kuvasz.status_page.enabled</code>.
     */
    public StatusPage setEnabled(Boolean enabled) {
        this.enabled = enabled;
        return this;
    }

    /**
     * Getter for <code>kuvasz.status_page.monitors</code>.
     */
    public MonitorID[] getMonitors() {
        return this.monitors;
    }

    /**
     * Setter for <code>kuvasz.status_page.monitors</code>.
     */
    public StatusPage setMonitors(MonitorID[] monitors) {
        this.monitors = monitors;
        return this;
    }

    /**
     * Getter for <code>kuvasz.status_page.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>kuvasz.status_page.created_at</code>.
     */
    public StatusPage setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * Getter for <code>kuvasz.status_page.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>kuvasz.status_page.updated_at</code>.
     */
    public StatusPage setUpdatedAt(OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final StatusPage other = (StatusPage) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.title == null) {
            if (other.title != null)
                return false;
        }
        else if (!this.title.equals(other.title))
            return false;
        if (this.slug == null) {
            if (other.slug != null)
                return false;
        }
        else if (!this.slug.equals(other.slug))
            return false;
        if (this.enabled == null) {
            if (other.enabled != null)
                return false;
        }
        else if (!this.enabled.equals(other.enabled))
            return false;
        if (this.monitors == null) {
            if (other.monitors != null)
                return false;
        }
        else if (!Arrays.deepEquals(this.monitors, other.monitors))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        result = prime * result + ((this.slug == null) ? 0 : this.slug.hashCode());
        result = prime * result + ((this.enabled == null) ? 0 : this.enabled.hashCode());
        result = prime * result + ((this.monitors == null) ? 0 : Arrays.deepHashCode(this.monitors));
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("StatusPage (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(slug);
        sb.append(", ").append(enabled);
        sb.append(", ").append(Arrays.deepToString(monitors));
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
