---
micronaut:
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
  security:
    enabled: true
    token:
      jwt:
        signatures:
          secret:
            generator:
              # Providing a hard-coded secret to prevent logouts in localdev env
              secret: cd961db8-54a1-4c09-b608-e528db09f74f
---
datasources:
  default:
    username: 'postgres'
    password: 'postgres'
---
admin-auth:
  username: user
  password: pass3j4hkhk23hk23k232hk3h232
  api-key: 3hjlkh23k2h3k2h3k2h3k2h3k2h3k2h3
---
smtp-config:
  host: ${SMTP_HOST:`sandbox.smtp.mailtrap.io`}
  port: ${SMTP_PORT:`465`}
---
logger:
  levels:
#    io.micronaut.http.client: TRACE
#    org.jooq: DEBUG
---
metrics-exports:
  http-uptime-status: true
  push-uptime-status: true
  http-latest-latency: true
  icmp-uptime-status: true
  icmp-latest-latency: true
  icmp-latest-packet-loss: true
  ssl-status: true
  ssl-expiry: true
---
http-monitors:
  - name: "Tralala #!: j[ő"
    url: "https://akobor.me"
    sensitive-url: true
    uptime-check-interval: 60
    enabled: true
    ssl-check-enabled: false
    latency-history-enabled: true
    request-method: "GET"
    follow-redirects: true
    force-no-cache: true
    ssl-expiry-threshold: 30
    failure-count-threshold: 1
    integrations: [ ]
    expected-status-codes: [ ]
    response-time-threshold-millis: null
    expected-keyword: null
    expected-keyword-case-sensitive: false
    expected-keyword-negated: false
    request-headers: { }
    expected-headers: { }
    request-body: null
  - name: "test1"
    url: "https://demo.kuvasz-uptime.dev"
    sensitive-url: false
    uptime-check-interval: 120
    enabled: true
    ssl-check-enabled: true
    latency-history-enabled: false
    request-method: "GET"
    follow-redirects: true
    force-no-cache: false
    ssl-expiry-threshold: 30
    failure-count-threshold: 1
    integrations: [ ]
    expected-status-codes:
      - 200
      - 201
      - 303
    response-time-threshold-millis: 500
    expected-keyword: "Kuvasz"
    expected-keyword-case-sensitive: true
    expected-keyword-negated: false
    request-headers: { }
    expected-headers: { }
    request-body: null
  - name: "test2"
    url: "https://kuvasz-uptime.dev"
    sensitive-url: false
    uptime-check-interval: 60
    enabled: true
    ssl-check-enabled: false
    latency-history-enabled: true
    request-method: "HEAD"
    follow-redirects: true
    force-no-cache: true
    ssl-expiry-threshold: 30
    failure-count-threshold: 1
    integrations: [ ]
    expected-status-codes: [ ]
    response-time-threshold-millis: null
    expected-keyword: null
    expected-keyword-case-sensitive: false
    expected-keyword-negated: false
    request-headers: { }
    expected-headers: { }
    request-body: null
push-monitors:
  - name: "Another Push Monitor"
    heartbeat-interval: 20
    grace-period: 3
    client-secret: "7b2d5cb1-41bd-4067-9732-c79dbbf45287"
    enabled: false
    integrations:
      - "slack:test"
    failure-count-threshold: 1
  - name: "My Push Monitor"
    heartbeat-interval: 10
    grace-period: 0
    client-secret: "d6d5a85c-82c0-4bea-9926-c3eed32de32a"
    enabled: true
    integrations: [ ]
    failure-count-threshold: 1
icmp-monitors:
  - name: "test"
    host: "github.com"
    uptime-check-interval: 5
    packet-count: 3
    timeout-seconds: 5
    packet-loss-threshold: 100
    failure-count-threshold: 1
    enabled: true
    integrations: [ ]
    metrics-history-enabled: true
  - name: "test2"
    host: "telex.hu"
    uptime-check-interval: 10
    packet-count: 3
    timeout-seconds: 5
    packet-loss-threshold: 10
    failure-count-threshold: 1
    enabled: true
    integrations: [ ]
    metrics-history-enabled: true
---
integrations:
  webhook:
    - name: webhook-test
      global: true
      excluded-events: [ ]
      url: http://localhost:8081/webhook
      request-headers:
        Something: "{{ctx.type}}"
    - name: webhook-templated
      global: true
      url: http://localhost:8081/webhook-templated
      excluded-events:
        - PUSH_UP
        - HTTP_UP
        - SSL_VALID
        - SSL_WILL_EXPIRE
      payload-template: |
        {
          "monitorName": "{{ctx.monitorName}}",
          "type": "{{ctx.type}}"
        }
  slack:
    - name: test
      webhook-url: https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXX
---
default-status-page:
  public: true
  title: "Default System Status"
---
status-pages:
  - title: "My Status Page"
    slug: test
    public: false
    monitors:
      - http:test2
