---
micronaut:
  security:
    enabled: true
    token:
      jwt:
        signatures:
          secret:
            generator:
              # Providing a hard-coded secret to prevent logouts in localdev env
              secret: cd961db8-54a1-4c09-b608-e528db09f74f
---
datasources:
  default:
    username: 'postgres'
    password: 'postgres'
---
handler-config:
  smtp-event-handler:
    enabled: ${ENABLE_SMTP_EVENT_HANDLER:`false`}
    from: ${SMTP_FROM_ADDRESS:`noreply@kuvasz.uptime`}
    to: ${SMTP_TO_ADDRESS:`recipient@kuvasz.uptime`}
  pagerduty-event-handler:
    enabled: false
---
admin-auth:
  username: user
  password: pass3j4hkhk23hk23k232hk3h232
  api-key: 3hjlkh23k2h3k2h3k2h3k2h3k2h3k2h3
---
smtp-config:
  host: ${SMTP_HOST:`sandbox.smtp.mailtrap.io`}
  port: ${SMTP_PORT:`465`}
---
logger:
  levels:
#    io.micronaut.http.client: TRACE
#    org.jooq: DEBUG
---
monitors:
  - name: test1
    url: http://example.com
    uptime-check-interval: 120
    enabled: false
    ssl-check-enabled: true
    pagerduty-integration-key: 1234567890abcdef
    request-method: HEAD
    latency-history-enabled: false
    force-no-cache: false
    follow-redirects: false
  - name: test2
    url: http://example.org
    uptime-check-interval: 60
