services:
  kuvasz-db:
    image: postgres:17-alpine
    container_name: kuvaszdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: "UTC"
    ports:
      - "5432:5432"
    volumes:
      - kuvasz-db-data:/var/lib/postgresql/data
  kuvasz:
    image: kuvaszmonitoring/kuvasz:latest
    container_name: kuvasz
    mem_limit: 384M # optional
    ports:
      - "8080:8080"
    environment:
      TZ: "UTC"
      DATABASE_HOST: kuvaszdb
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      ADMIN_USER: admin # change it
      ADMIN_PASSWORD: adminsecurepass123 # change it
      ADMIN_API_KEY: adminapikeysecure456 # change it
    volumes:
      - ./kuvasz.yml:/config/kuvasz.yml
    depends_on:
      - kuvasz-db
volumes:
  kuvasz-db-data:
