/*
 * This file is generated by jOOQ.
 */
package com.kuvaszuptime.kuvasz.tables.records;


import com.kuvaszuptime.kuvasz.enums.UptimeStatus;
import com.kuvaszuptime.kuvasz.tables.UptimeEvent;

import java.time.OffsetDateTime;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "uptime_event", uniqueConstraints = {
    @UniqueConstraint(name = "uptime_event_pkey", columnNames = {"id"}),
    @UniqueConstraint(name = "uptime_event_key", columnNames = {"monitor_id", "status", "ended_at"})
}, indexes = {
    @Index(name = "uptime_event_ended_at_idx", columnList = "ended_at ASC"),
    @Index(name = "uptime_event_monitor_idx", columnList = "monitor_id ASC")
})
public class UptimeEventRecord extends UpdatableRecordImpl<UptimeEventRecord> implements Record6<Integer, Integer, UptimeStatus, String, OffsetDateTime, OffsetDateTime> {

    private static final long serialVersionUID = 187938053;

    /**
     * Setter for <code>uptime_event.id</code>.
     */
    public UptimeEventRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>uptime_event.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false, precision = 32)
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>uptime_event.monitor_id</code>.
     */
    public UptimeEventRecord setMonitorId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>uptime_event.monitor_id</code>.
     */
    @Column(name = "monitor_id", nullable = false, precision = 32)
    @NotNull
    public Integer getMonitorId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>uptime_event.status</code>. Status of the event
     */
    public UptimeEventRecord setStatus(UptimeStatus value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>uptime_event.status</code>. Status of the event
     */
    @Column(name = "status", nullable = false)
    @NotNull
    public UptimeStatus getStatus() {
        return (UptimeStatus) get(2);
    }

    /**
     * Setter for <code>uptime_event.error</code>.
     */
    public UptimeEventRecord setError(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>uptime_event.error</code>.
     */
    @Column(name = "error")
    public String getError() {
        return (String) get(3);
    }

    /**
     * Setter for <code>uptime_event.started_at</code>. The current event started at
     */
    public UptimeEventRecord setStartedAt(OffsetDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>uptime_event.started_at</code>. The current event started at
     */
    @Column(name = "started_at", nullable = false)
    public OffsetDateTime getStartedAt() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>uptime_event.ended_at</code>. The current event ended at
     */
    public UptimeEventRecord setEndedAt(OffsetDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>uptime_event.ended_at</code>. The current event ended at
     */
    @Column(name = "ended_at")
    public OffsetDateTime getEndedAt() {
        return (OffsetDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Integer, UptimeStatus, String, OffsetDateTime, OffsetDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, Integer, UptimeStatus, String, OffsetDateTime, OffsetDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return UptimeEvent.UPTIME_EVENT.ID;
    }

    @Override
    public Field<Integer> field2() {
        return UptimeEvent.UPTIME_EVENT.MONITOR_ID;
    }

    @Override
    public Field<UptimeStatus> field3() {
        return UptimeEvent.UPTIME_EVENT.STATUS;
    }

    @Override
    public Field<String> field4() {
        return UptimeEvent.UPTIME_EVENT.ERROR;
    }

    @Override
    public Field<OffsetDateTime> field5() {
        return UptimeEvent.UPTIME_EVENT.STARTED_AT;
    }

    @Override
    public Field<OffsetDateTime> field6() {
        return UptimeEvent.UPTIME_EVENT.ENDED_AT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getMonitorId();
    }

    @Override
    public UptimeStatus component3() {
        return getStatus();
    }

    @Override
    public String component4() {
        return getError();
    }

    @Override
    public OffsetDateTime component5() {
        return getStartedAt();
    }

    @Override
    public OffsetDateTime component6() {
        return getEndedAt();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getMonitorId();
    }

    @Override
    public UptimeStatus value3() {
        return getStatus();
    }

    @Override
    public String value4() {
        return getError();
    }

    @Override
    public OffsetDateTime value5() {
        return getStartedAt();
    }

    @Override
    public OffsetDateTime value6() {
        return getEndedAt();
    }

    @Override
    public UptimeEventRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public UptimeEventRecord value2(Integer value) {
        setMonitorId(value);
        return this;
    }

    @Override
    public UptimeEventRecord value3(UptimeStatus value) {
        setStatus(value);
        return this;
    }

    @Override
    public UptimeEventRecord value4(String value) {
        setError(value);
        return this;
    }

    @Override
    public UptimeEventRecord value5(OffsetDateTime value) {
        setStartedAt(value);
        return this;
    }

    @Override
    public UptimeEventRecord value6(OffsetDateTime value) {
        setEndedAt(value);
        return this;
    }

    @Override
    public UptimeEventRecord values(Integer value1, Integer value2, UptimeStatus value3, String value4, OffsetDateTime value5, OffsetDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UptimeEventRecord
     */
    public UptimeEventRecord() {
        super(UptimeEvent.UPTIME_EVENT);
    }

    /**
     * Create a detached, initialised UptimeEventRecord
     */
    public UptimeEventRecord(Integer id, Integer monitorId, UptimeStatus status, String error, OffsetDateTime startedAt, OffsetDateTime endedAt) {
        super(UptimeEvent.UPTIME_EVENT);

        set(0, id);
        set(1, monitorId);
        set(2, status);
        set(3, error);
        set(4, startedAt);
        set(5, endedAt);
    }
}
