apiVersion: v2
name: kuvasz-uptime
description: A Helm chart for Kubernetes to install Kuvasz Uptime - An open-source, self-hosted uptime & SSL monitoring service with status pages
type: application
version: 0.1.0
appVersion: "latest"
keywords:
  - monitoring
  - uptime
  - status-page
  - alerting
home: https://kuvasz-uptime.dev
sources:
  - https://github.com/kuvasz-uptime/kuvasz
maintainers:
  - name: Kuvasz Team

