package com.kuvaszuptime.kuvasz.util

object UIDefaults {
    const val DASHBOARD_MONITORING_STATS_PERIOD_DAYS = 7L
    const val HTTP_MONITOR_UPTIME_STATS_PERIOD_DAYS = 7L
    const val PUSH_MONITOR_UPTIME_STATS_PERIOD_DAYS = 7L
    const val ICMP_MONITOR_UPTIME_STATS_PERIOD_DAYS = 7L
    const val TCP_MONITOR_UPTIME_STATS_PERIOD_DAYS = 7L
    const val DNS_MONITOR_UPTIME_STATS_PERIOD_DAYS = 7L
    const val MONITOR_METRICS_PERIOD_DAYS = 1L
    const val INCIDENTS_PERIOD_DAYS = 7L
    const val STATUS_PAGE_PATH = "/status"
}
