/*
 * This file is generated by jOOQ.
 */
package com.akobor.kuvasz.enums;


import com.akobor.kuvasz.DefaultSchema;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum UptimeStatus implements EnumType {

    UP("UP"),

    DOWN("DOWN");

    private final String literal;

    private UptimeStatus(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema() == null ? null : getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public String getName() {
        return "uptime_status";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
