/*
 * This file is generated by jOOQ.
 */
package com.kuvaszuptime.kuvasz.tables.daos;


import com.kuvaszuptime.kuvasz.tables.PagerdutyIncident;
import com.kuvaszuptime.kuvasz.tables.pojos.PagerdutyIncidentPojo;
import com.kuvaszuptime.kuvasz.tables.records.PagerdutyIncidentRecord;

import java.time.OffsetDateTime;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PagerdutyIncidentDao extends DAOImpl<PagerdutyIncidentRecord, PagerdutyIncidentPojo, Integer> {

    /**
     * Create a new PagerdutyIncidentDao without any configuration
     */
    public PagerdutyIncidentDao() {
        super(PagerdutyIncident.PAGERDUTY_INCIDENT, PagerdutyIncidentPojo.class);
    }

    /**
     * Create a new PagerdutyIncidentDao with an attached configuration
     */
    public PagerdutyIncidentDao(Configuration configuration) {
        super(PagerdutyIncident.PAGERDUTY_INCIDENT, PagerdutyIncidentPojo.class, configuration);
    }

    @Override
    public Integer getId(PagerdutyIncidentPojo object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<PagerdutyIncidentPojo> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(PagerdutyIncident.PAGERDUTY_INCIDENT.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<PagerdutyIncidentPojo> fetchById(Integer... values) {
        return fetch(PagerdutyIncident.PAGERDUTY_INCIDENT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public PagerdutyIncidentPojo fetchOneById(Integer value) {
        return fetchOne(PagerdutyIncident.PAGERDUTY_INCIDENT.ID, value);
    }

    /**
     * Fetch records that have <code>uptime_event_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<PagerdutyIncidentPojo> fetchRangeOfUptimeEventId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(PagerdutyIncident.PAGERDUTY_INCIDENT.UPTIME_EVENT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>uptime_event_id IN (values)</code>
     */
    public List<PagerdutyIncidentPojo> fetchByUptimeEventId(Integer... values) {
        return fetch(PagerdutyIncident.PAGERDUTY_INCIDENT.UPTIME_EVENT_ID, values);
    }

    /**
     * Fetch records that have <code>ssl_event_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<PagerdutyIncidentPojo> fetchRangeOfSslEventId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(PagerdutyIncident.PAGERDUTY_INCIDENT.SSL_EVENT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ssl_event_id IN (values)</code>
     */
    public List<PagerdutyIncidentPojo> fetchBySslEventId(Integer... values) {
        return fetch(PagerdutyIncident.PAGERDUTY_INCIDENT.SSL_EVENT_ID, values);
    }

    /**
     * Fetch records that have <code>deduplication_key BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<PagerdutyIncidentPojo> fetchRangeOfDeduplicationKey(String lowerInclusive, String upperInclusive) {
        return fetchRange(PagerdutyIncident.PAGERDUTY_INCIDENT.DEDUPLICATION_KEY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>deduplication_key IN (values)</code>
     */
    public List<PagerdutyIncidentPojo> fetchByDeduplicationKey(String... values) {
        return fetch(PagerdutyIncident.PAGERDUTY_INCIDENT.DEDUPLICATION_KEY, values);
    }

    /**
     * Fetch records that have <code>started_at BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<PagerdutyIncidentPojo> fetchRangeOfStartedAt(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(PagerdutyIncident.PAGERDUTY_INCIDENT.STARTED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>started_at IN (values)</code>
     */
    public List<PagerdutyIncidentPojo> fetchByStartedAt(OffsetDateTime... values) {
        return fetch(PagerdutyIncident.PAGERDUTY_INCIDENT.STARTED_AT, values);
    }

    /**
     * Fetch records that have <code>ended_at BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<PagerdutyIncidentPojo> fetchRangeOfEndedAt(OffsetDateTime lowerInclusive, OffsetDateTime upperInclusive) {
        return fetchRange(PagerdutyIncident.PAGERDUTY_INCIDENT.ENDED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>ended_at IN (values)</code>
     */
    public List<PagerdutyIncidentPojo> fetchByEndedAt(OffsetDateTime... values) {
        return fetch(PagerdutyIncident.PAGERDUTY_INCIDENT.ENDED_AT, values);
    }
}
