/*
 * This file is generated by jOOQ.
 */
package com.akobor.kuvasz;


import com.akobor.kuvasz.tables.LatencyLog;
import com.akobor.kuvasz.tables.Monitor;
import com.akobor.kuvasz.tables.UptimeEvent;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 255525230;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>latency_log</code>.
     */
    public final LatencyLog LATENCY_LOG = LatencyLog.LATENCY_LOG;

    /**
     * The table <code>monitor</code>.
     */
    public final Monitor MONITOR = Monitor.MONITOR;

    /**
     * The table <code>uptime_event</code>.
     */
    public final UptimeEvent UPTIME_EVENT = UptimeEvent.UPTIME_EVENT;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.LATENCY_LOG_ID_SEQ,
            Sequences.MONITOR_ID_SEQ,
            Sequences.UPTIME_EVENT_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            LatencyLog.LATENCY_LOG,
            Monitor.MONITOR,
            UptimeEvent.UPTIME_EVENT);
    }
}
