/*
 * This file is generated by jOOQ.
 */
package com.akobor.kuvasz;


import com.akobor.kuvasz.tables.LatencyLog;
import com.akobor.kuvasz.tables.Monitor;
import com.akobor.kuvasz.tables.UptimeEvent;


/**
 * Convenience access to all tables in 
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>latency_log</code>.
     */
    public static final LatencyLog LATENCY_LOG = LatencyLog.LATENCY_LOG;

    /**
     * The table <code>monitor</code>.
     */
    public static final Monitor MONITOR = Monitor.MONITOR;

    /**
     * The table <code>uptime_event</code>.
     */
    public static final UptimeEvent UPTIME_EVENT = UptimeEvent.UPTIME_EVENT;
}
