/*
 * This file is generated by jOOQ.
 */
package com.kuvaszuptime.kuvasz.jooq.enums;


import com.kuvaszuptime.kuvasz.jooq.Kuvasz;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public enum DnsTransport implements EnumType {

    UDP("UDP"),

    TCP("TCP");

    private final String literal;

    private DnsTransport(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Kuvasz.KUVASZ;
    }

    @Override
    public String getName() {
        return "dns_transport";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal. Returns
     * <code>null</code>, if no such value could be found, see {@link
     * EnumType#lookupLiteral(Class, String)}.
     */
    public static DnsTransport lookupLiteral(String literal) {
        return EnumType.lookupLiteral(DnsTransport.class, literal);
    }
}
