site_name: Kuvasz Uptime
repo_url: https://github.com/kuvasz-uptime/kuvasz
theme:
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    tag:
      min_ver: material/tag
  name: material
  logo: images/kuvasz-logo.png
  favicon: images/favicon.png
  custom_dir: overrides
  features:
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - announce.dismiss
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - search
  - redoc-tag
  - glightbox:
      skip_classes:
        - skip-lb
extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  analytics:
    provider: google
    property: G-390JFEVMCZ
  tags:
    min_ver: Minimum version
hooks:
  - overrides/hooks/shortcodes.py
extra_css:
  - stylesheets/custom.css
nav:
  - Introduction: index.md
  - Getting Started:
      - Installation: setup/installation.md
      - Configuration: setup/configuration.md
      - Integrations setup: setup/integrations.md
      - Creating Monitors: setup/creating-monitors.md
      - Recipes & Examples: setup/examples.md
  - Features:
      - Uptime Monitoring: features/uptime-monitoring.md
      - SSL Monitoring: features/ssl-monitoring.md
      - Integrations: features/integrations.md
      - Web UI: features/ui.md
      - Flexibility: features/flexibility.md
      - Performance: features/performance.md
      - API: features/api.md
  - Localization: localization.md
  - API docs: api-doc.md
  - Changelog: changelog.md
  - Conventions: conventions.md
copyright: Copyright &copy; 2020 - 2025 Kuvasz Uptime
