name: Build docs
on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'docker-examples/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'docker-examples/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: 3.14
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v6
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: docs/.cache
          restore-keys: |
            mkdocs-material-
      - run: pip install -r requirements.txt
        working-directory: docs
      - run: mkdocs build --strict
        working-directory: docs
